### ISSUE TITLE
Reading mortality variable once lethal temperature is set

### ISSUE THREAD

**Issue by Ideschepper** [ichthyop/ichthyop#10]
Hello,

My colleague and I are struggling to find how we interpret the mortality variable when a lethal min and max temperature had been set. 
We see that there is a value from 0 to 6, but we do not find information on what these values mean. Could you help us out?
With that once the particle has died, is it correct to assume that the value in the coordinate files would read NA or will the coordinates remain the same from the time of death to the end of the simulation time?

Many thanks in advance,
Inge Deschepper and Sarah Schembri

**Comment by barriern** [comment]
Hi Inge, Hi Sarah

In the output NetCDF file, the mortality attributes describe the meaning of the mortality array:

`		mortality:alive = 0 ;
		mortality:dead_cold = 1 ;
		mortality:out_of_domain = 2 ;
		mortality:old = 3 ;
		mortality:beached = 4 ;
		mortality:starvation = 5 ;
		mortality:dead_hot = 6 ;
		mortality:dead_fresh = 7 ;
		mortality:dead_saline = 8 ;
`

When a particule dies, it remains still. So if you want to remove dead particules, you have to mask the longitudes and latitudes where mortality > 0. In Python, it would give something like this:

`
import numpy as np
lon = np.ma.masked_where(mortality > 0, lon)
lat = np.ma.masked_where(mortality > 0, lat)
`

Nicolas

**Comment by Ideschepper** [comment]
HI Nicolas,

Thank you very much! Exactly what we needed :)

Inge
