### ISSUE TITLE
Read Stokes Velocity

### ISSUE THREAD

**Issue by xzhou473** [ichthyop/ichthyop#103]
Hi,

It is really excited to see the latest version of Ichthyop, including the read option for Stokes velocity from ROMS 3D.

I noticed the "read_stokesvelocity" option in the Roms3dCommon.java file. However, when I use the 3.3.17 GUI to create a new XML file for ROMS 3D, there appears to be no parameter related to Stokes velocity (see the attached figure).

Could you possibly share an example of an XML file that includes the Stokes velocity option, or what edit I can make to the XML file to include the Stokes velocity?

Thank you!

![Screen Shot 2024-06-26 at 2 14 51 PM](https://github.com/ichthyop/ichthyop/assets/134965827/d3380fee-a7e5-4ba7-a620-71e29f7adad7)

**Comment by barriern** [comment]
Hi @xzhou473

When trying to answer your question, I noticed some bugs in the Stokes part of the `Roms3dCommon.java` file. In order to correct them, could you please send me, via WeTransfer or anything similar, a snapshot of a Roms file containing the Stokes velocity outputs? Thanks

Nicolas

**Comment by xzhou473** [comment]
Hi barriern,

Here is the one example of output containing the Stokes velocity (bolded). Let me know if you need anything else.

netcdf croco_avg.00008 {
dimensions:
	xi_rho = 1595 ;
	xi_u = 1594 ;
	eta_rho = 774 ;
	eta_v = 773 ;
	s_rho = 70 ;
	s_w = 71 ;
	time = UNLIMITED ; // (1 currently)
	auxil = 4 ;
variables:
	int time_step(time, auxil) ;
		time_step:long_name = "time step and record numbers from initialization" ;
	double scrum_time(time) ;
		scrum_time:long_name = "averaged time since initialization" ;
		scrum_time:units = "second" ;
		scrum_time:field = "time, scalar, series" ;
		scrum_time:standard_name = "time" ;
		scrum_time:axis = "T" ;
	double time(time) ;
		time:long_name = "averaged time since initialization" ;
		time:units = "second" ;
		time:field = "time, scalar, series" ;
		time:standard_name = "time" ;
		time:axis = "T" ;
	float zeta(time, eta_rho, xi_rho) ;
		zeta:long_name = "averaged free-surface" ;
		zeta:units = "meter" ;
		zeta:field = "free-surface, scalar, series" ;
		zeta:standard_name = "sea_surface_height" ;
		zeta:coordinates = "lat_rho lon_rho" ;
	float u(time, s_rho, eta_rho, xi_u) ;
		u:long_name = "averaged u-momentum component" ;
		u:units = "meter second-1" ;
		u:field = "u-velocity, scalar, series" ;
		u:standard_name = "sea_water_x_velocity_at_u_location" ;
		u:coordinates = "lat_u lon_u" ;
	float v(time, s_rho, eta_v, xi_rho) ;
		v:long_name = "averaged v-momentum component" ;
		v:units = "meter second-1" ;
		v:field = "v-velocity, scalar, series" ;
		v:standard_name = "sea_water_y_velocity_at_v_location" ;
		v:coordinates = "lat_v lon_v" ;
	float temp(time, s_rho, eta_rho, xi_rho) ;
		temp:long_name = "averaged potential temperature" ;
		temp:units = "Celsius" ;
		temp:field = "temperature, scalar, series" ;
		temp:standard_name = "sea_water_potential_temperature" ;
		temp:coordinates = "lat_rho lon_rho" ;
	float salt(time, s_rho, eta_rho, xi_rho) ;
		salt:long_name = "averaged salinity" ;
		salt:units = "PSU" ;
		salt:field = "salinity, scalar, series" ;
		salt:standard_name = "sea_water_salinity" ;
		salt:coordinates = "lat_rho lon_rho" ;
	float w(time, s_rho, eta_rho, xi_rho) ;
		w:long_name = "averaged vertical momentum component" ;
		w:units = "meter second-1" ;
		w:field = "w-velocity, scalar, series" ;
		w:standard_name = "upward_sea_water_velocity" ;
		w:coordinates = "lat_rho lon_rho" ;
	**float ust(time, s_rho, eta_rho, xi_u) ;
		ust:long_name = "averaged u 3D Stokes drift velocity" ;
		ust:units = "meter second-1" ;
	float vst(time, s_rho, eta_v, xi_rho) ;
		vst:long_name = "averaged u 3D Stokes drift velocity" ;
		vst:units = "meter second-1" ;
	float wst(time, s_rho, eta_rho, xi_rho) ;
		wst:long_name = "averaged w vertical 3D Stokes drift velocity" ;
		wst:units = "meter second-1" ;**

// global attributes:
		:type = "CROCO averages file" ;
		:title = "croco3P5km from 20131001" ;
		:date = "" ;
		:rst_file = "/storage/home/hcoda1/9/xzhou473/scratch/MP_GOM/CROCO_daoxun/output_snapshot/croco_rst.nc" ;
		:his_file = "/storage/home/hcoda1/9/xzhou473/scratch/MP_GOM/CROCO_daoxun/output_snapshot/croco_his.00009.nc" ;
		:avg_file = "/storage/home/hcoda1/9/xzhou473/scratch/MP_GOM/CROCO_daoxun/output_snapshot/croco_avg.00008.nc" ;
		:grd_file = "./gmx1km_grd.nc" ;
		:ini_file = "./GOM1km_rst.00005.nc" ;
		:frc_file = "./GOM_frc_tides_201312_201404.nc" ;
		:qbar_file = "./GOM1km_rivTS_201401_201404.nc" ;
		:VertCoordType = "NEW" ;
		:theta_s = 5.f ;
		:theta_s_expl = "S-coordinate surface control parameter" ;
		:theta_b = 0.4f ;
		:theta_b_expl = "S-coordinate bottom control parameter" ;
		:Tcline = 30.f ;
		:Tcline_expl = "S-coordinate surface/bottom layer width" ;
		:Tcline_units = "meter" ;
		:hc = 30.f ;
		:hc_expl = "S-coordinate parameter, critical depth" ;
		:hc_units = "meter" ;
		:sc_w = -1.f, -0.9857143f, -0.9714286f, -0.9571428f, -0.9428571f, -0.9285714f, -0.9142857f, -0.9f, -0.8857143f, -0.8714285f, -0.8571429f, -0.8428571f, -0.8285714f, -0.8142857f, -0.8f, -0.7857143f, -0.7714286f, -0.7571428f, -0.7428572f, -0.7285714f, -0.7142857f, -0.7f, -0.6857143f, -0.6714286f, -0.6571429f, -0.6428571f, -0.6285715f, -0.6142857f, -0.6f, -0.5857143f, -0.5714286f, -0.5571429f, -0.5428572f, -0.5285714f, -0.5142857f, -0.5f, -0.4857143f, -0.4714286f, -0.4571429f, -0.4428571f, -0.4285714f, -0.4142857f, -0.4f, -0.3857143f, -0.3714286f, -0.3571429f, -0.3428572f, -0.3285714f, -0.3142857f, -0.3f, -0.2857143f, -0.2714286f, -0.2571429f, -0.2428571f, -0.2285714f, -0.2142857f, -0.2f, -0.1857143f, -0.1714286f, -0.1571429f, -0.1428571f, -0.1285714f, -0.1142857f, -0.1f, -0.08571429f, -0.07142857f, -0.05714286f, -0.04285714f, -0.02857143f, -0.01428571f, 0.f ;
		:sc_w_expl = "S-coordinate at W-points" ;
		:Cs_w = -1.f, -0.9423714f, -0.8872486f, -0.8346207f, -0.7844617f, -0.7367329f, -0.6913848f, -0.6483588f, -0.6075894f, -0.569005f, -0.5325298f, -0.4980848f, -0.4655891f, -0.4349602f, -0.4061157f, -0.3789732f, -0.3534512f, -0.3294696f, -0.3069499f, -0.285816f, -0.2659936f, -0.2474113f, -0.2300002f, -0.2136939f, -0.1984292f, -0.1841454f, -0.1707847f, -0.158292f, -0.1466152f, -0.1357045f, -0.1255132f, -0.1159967f, -0.107113f, -0.09882277f, -0.09108853f, -0.0838752f, -0.07714979f, -0.07088124f, -0.06504045f, -0.05960011f, -0.0545346f, -0.04981996f, -0.04543377f, -0.04135505f, -0.03756423f, -0.03404303f, -0.0307744f, -0.02774248f, -0.02493249f, -0.02233068f, -0.01992433f, -0.01770159f, -0.01565152f, -0.013764f, -0.0120297f, -0.01044001f, -0.008987057f, -0.007663608f, -0.006463076f, -0.005379476f, -0.004407401f, -0.003541996f, -0.002778931f, -0.002114389f, -0.001545042f, -0.001068037f, -0.0006809809f, -0.0003819334f, -0.0001693938f, -4.229538e-05f, 0.f ;
		:Cs_w_expl = "S-coordinate stretching curves at W-points" ;
		:sc_r = -0.9928572f, -0.9785714f, -0.9642857f, -0.95f, -0.9357143f, -0.9214286f, -0.9071429f, -0.8928571f, -0.8785715f, -0.8642857f, -0.85f, -0.8357143f, -0.8214286f, -0.8071429f, -0.7928572f, -0.7785714f, -0.7642857f, -0.75f, -0.7357143f, -0.7214286f, -0.7071428f, -0.6928571f, -0.6785714f, -0.6642857f, -0.65f, -0.6357143f, -0.6214285f, -0.6071429f, -0.5928571f, -0.5785714f, -0.5642857f, -0.55f, -0.5357143f, -0.5214286f, -0.5071428f, -0.4928571f, -0.4785714f, -0.4642857f, -0.45f, -0.4357143f, -0.4214286f, -0.4071428f, -0.3928571f, -0.3785714f, -0.3642857f, -0.35f, -0.3357143f, -0.3214286f, -0.3071429f, -0.2928571f, -0.2785714f, -0.2642857f, -0.25f, -0.2357143f, -0.2214286f, -0.2071429f, -0.1928571f, -0.1785714f, -0.1642857f, -0.15f, -0.1357143f, -0.1214286f, -0.1071429f, -0.09285714f, -0.07857143f, -0.06428572f, -0.05f, -0.03571429f, -0.02142857f, -0.007142857f ;
		:sc_r_expl = "S-coordinate at W-points" ;
		:Cs_r = -0.9708725f, -0.9144971f, -0.8606241f, -0.8092347f, -0.7602964f, -0.7137647f, -0.6695855f, -0.6276964f, -0.5880287f, -0.5505086f, -0.5150586f, -0.4815984f, -0.4500464f, -0.4203201f, -0.3923368f, -0.3660147f, -0.3412728f, -0.3180318f, -0.2962144f, -0.2757454f, -0.2565518f, -0.2385636f, -0.221713f, -0.2059353f, -0.1911684f, -0.1773532f, -0.1644332f, -0.1523548f, -0.1410671f, -0.1305218f, -0.1206732f, -0.1114783f, -0.1028961f, -0.09488839f, -0.08741886f, -0.08045349f, -0.07396027f, -0.06790913f, -0.06227187f, -0.05702204f, -0.05213486f, -0.04758715f, -0.04335723f, -0.03942483f, -0.03577102f, -0.03237816f, -0.0292298f, -0.02631062f, -0.02360638f, -0.02110384f, -0.01879071f, -0.01665562f, -0.01468804f, -0.01287825f, -0.01121729f, -0.00969691f, -0.00830957f, -0.007048365f, -0.00590701f, -0.004879814f, -0.003961647f, -0.003147921f, -0.002434564f, -0.001818006f, -0.001295157f, -0.0008633968f, -0.0005205601f, -0.0002649269f, -9.521435e-05f, -1.057053e-05f ;
		:Cs_r_expl = "S-coordinate stretching curves at RHO-points" ;
		:ntimes = 259920 ;
		:ndtfast = 10 ;
		:dt = 20.f ;
		:dtfast = 2.f ;
		:nwrt = 180 ;
		:ntsavg = 1 ;
		:ntsavg_expl = "starting time-step for accumulation of time-averaged fields" ;
		:navg = 180 ;
		:navg_expl = "number of time-steps between time-averaged records" ;
		:visc2 = 5.f ;
		:visc2_expl = "Laplacian mixing coefficient for momentum" ;
		:visc2_units = "meter2 second-1" ;
		:tnu4 = 0.01f ;
		:tnu4_expl = "biharmonic mixing coefficient for tracers" ;
		:units = "meter4 second-1" ;
		:rdrg2 = 0.003f ;
		:rdrg2_expl = "quadratic drag coefficient" ;
		:rdrg2_units = "nondimensional" ;
		:rho0 = 1025.f ;
		:rho0_expl = "Mean density used in Boussinesq approximation" ;
		:rho0_units = "kilogram meter-3" ;
		:gamma2 = 1.f ;
		:gamma2_expl = "Slipperiness parameter" ;
		:SRCS = "main.F step.F read_inp.F timers_roms.F init_scalars.F init_arrays.F set_weights.F set_scoord.F ana_grid.F setup_grid1.F setup_grid2.F set_nudgcof.F ana_initial.F analytical.F zonavg.F step2d.F u2dbc.F v2dbc.F zetabc.F obc_volcons.F pre_step3d.F step3d_t.F step3d_uv1.F step3d_uv2.F prsgrd.F rhs3d.F set_depth.F omega.F uv3dmix.F uv3dmix_spg.F t3dmix.F t3dmix_spg.F hmix_coef.F wetdry.F wavedry.F u3dbc.F v3dbc.F t3dbc.F step3d_fast.F step3d_w.F rhs3d_w_nh.F initial_nbq.F grid_nbq.F unbq_bc.F vnbq_bc.F wnbq_bc.F rnbq_bc.F w3dbc.F nbq_bry_store.F rho_eos.F ab_ratio.F alfabeta.F alfabeta_k.F ana_vmix.F bvf_mix.F lmd_vmix.F gls_mixing.F lmd_skpp.F lmd_bkpp.F lmd_swfrac.F lmd_wscale.F diag.F wvlcty.F checkdims.F grid_stiffness.F bio_diag.F setup_kwds.F check_kwds.F check_srcs.F check_switches1.F check_switches2.F debug.F param.F ncscrum.F scalars.F output.F put_global_atts.F nf_fread.F nf_fread_x.F nf_fread_y.F nf_read_bry.F get_date.F lenstr.F closecdf.F insert_node.F fillvalue.F nf_add_attribute.F set_cycle.F def_grid_2d.F def_grid_3d.F def_his.F def_rst.F def_diags.F def_diagsM.F def_bio_diags.F wrt_grid.F wrt_his.F wrt_avg.F wrt_rst.F wrt_diags.F wrt_diags_avg.F wrt_diagsM.F wrt_diagsM_avg.F wrt_bio_diags.F wrt_bio_diags_avg.F set_avg.F set_diags_avg.F set_diagsM_avg.F set_bio_diags_avg.F def_diags_vrt.F wrt_diags_vrt.F set_diags_vrt.F set_diags_vrt_avg.F wrt_diags_vrt_avg.F def_diags_ek.F wrt_diags_ek.F set_diags_ek.F set_diags_ek_avg.F wrt_diags_ek_avg.F def_diags_pv.F wrt_diags_pv.F set_diags_pv.F set_diags_pv_avg.F wrt_diags_pv_avg.F def_diags_eddy.F set_diags_eddy_avg.F wrt_diags_eddy_avg.F def_surf.F wrt_surf.F set_surf_avg.F wrt_surf_avg.F get_grid.F get_initial.F get_vbc.F get_wwave.F get_tclima.F get_uclima.F get_ssh.F get_sss.F get_smflux.F get_stflux.F get_srflux.F get_sst.F mod_tides_mas.F tidedata.F mas.F get_tides.F clm_tides.F get_bulk.F bulk_flux.F get_bry.F get_bry_bio.F sstskin.F get_psource.F get_psource_ts.F get_btflux.F mrl_wci.F wkb_wwave.F wkbbc.F get_bry_wkb.F online_bulk_var.F online_get_bulk.F online_interp.F online_interpolate_bulk.F online_set_bulk.F init_floats.F wrt_floats.F step_floats.F rhs_floats.F interp_rho.F def_floats.F init_arrays_floats.F random_walk.F get_initial_floats.F init_sta.F wrt_sta.F step_sta.F interp_sta.F def_sta.F init_arrays_sta.F biology.F o2sato.F sediment.F bbl.F MPI_Setup.F MessPass2D.F MessPass3D.F exchange.F autotiling.F zoom.F update2D.F set_nudgcof_fine.F zoombc_2D.F zoombc_3D.F uv3dpremix.F t3dpremix.F update3D.F zoombc_3Dfast.F Agrif2Model.F send_xios_diags.F cpl_prism_define.F cpl_prism_put.F cpl_prism_init.F cpl_prism_get.F cpl_prism_getvar.F cpl_prism_grid.F module_substance.F module_MUSTANG.F online_spectral_diags.F var3d_oa_out.F var2d_oa_out.F scal0d_oa_out_loc.F scal0d_oa_out_full.F output_oa.F par_pisces.F90 ocean2pisces.F90 trc.F90 sms_pisces.F90 p4zche.F90 p4zint.F90 p4zlys.F90 p4zflx.F90 p4zlim.F90 p4zsink.F90 p4zmicro.F90 p4zmeso.F90 p4zmort.F90 p4zopt.F90 p4zprod.F90 p4zrem.F90 p4zsbc.F90 p4zsed.F90 trcwri_pisces.F90 p4zagg.F90 p4zfechem.F90 p4zligand.F90 p4zpoc.F90 p4zsms.F90 p5zlim.F90 p5zmeso.F90 p5zmicro.F90 p5zmort.F90 p5zprod.F90 p4zbio.F90 trcsms_pisces.F90 trcini_pisces.F90 pisces_ini.F90 oce_sed.F90 par_sed.F90 sedadv.F90 sedarr.F90 sedbtb.F90 sedchem.F90 sedco3.F90 seddiff.F90 seddsr.F90 seddta.F90 sed.F90 sedini.F90 sedinitrc.F90 sedinorg.F90 sedmat.F90 sedmbc.F90 sedmodel.F90 sed_oce.F90 sedorg.F90 sedrst.F90 sedsfc.F90 sedstp.F90 sedwri.F90 setavg_sed.F90 module_parameter_oa.F90 module_grd_oa.F90 module_oa_time.F90 module_oa_space.F90 module_oa_periode.F90 module_oa_variables.F90 module_oa_type.F90 module_tile_oa.F90 module_oa_level.F90 module_oa_interface.F90 var_oa.F90 tooldatosec.F90 toolsectodat.F90 tooldecompdat.F90 tooldatetosec.F90 toolorigindate.F90 flocmod.F90 comsubstance.F90 substance.F90 comMUSTANG.F90 coupler_MUSTANG.F90 sed_MUSTANG_CROCO.F90 sed_MUSTANG.F90 initMUSTANG.F90 plug_MUSTANG_CROCO.F90" ;
		:CPP-options = "COASTAL GOM1km MPI MRL_WCI TIDES OBC_EAST OBC_SOUTH NC4PAR CURVGRID SPHERICAL MASKING NEW_S_COORD SOLVE3D UV_COR UV_ADV SALINITY NONLIN_EOS SPLIT_EOS BULK_FLUX BULK_LW FRC_BRY Z_FRC_BRY M2_FRC_BRY T_FRC_BRY UV_HADV_UP3 UV_VIS2 UV_VIS_SMAGO UV_VADV_WENO5 TS_HADV_RSUP3 TS_DIF4 TS_VADV_WENO5 SPONGE LIMIT_BSTRESS LMD_MIXING LMD_BKPP LMD_RIMIX LMD_CONVEC WKB_WWAVE WAVE_FRICTION WKB_OBC_SOUTH WKB_OBC_EAST ANA_BSFLUX ANA_BTFLUX PSOURCE PSOURCE_NCFILE PSOURCE_NCFILE_TS SSH_TIDES UV_TIDES POT_TIDES TIDERAMP OBC_M2CHARACT OBC_M3ORLANSKI OBC_TORLANSKI AVERAGES AVERAGES_K STOKES_DRIFT UV_MIX_S TS_HADV_C4 TS_MIX_IMP DIF_COEF_3D BULK_FAIRALL BULK_EP BULK_SMFLUX OBC_M2FLATHER ANA_PSOURCE M2FILTER_POWER TRACERS TEMPERATURE HZR VAR_RHO_2D VIS_COEF_3D TS_MIX_ISO TS_MIX_ISO_FILT NTRA_T3DMIX SPONGE_GRID SPONGE_DIF2 SPONGE_VIS2 WAVE_BREAK_CT93 WKB_ADD_DIFF WKB_ADD_DIFFRACTION WAVE_IO NF_CLOBBER" ;

**Comment by barriern** [comment]
Hi  @xzhou473 

I have made a new Ichthyop release with the Stokes bug fix (3.3.17.3). Here is also a sample configuration file which allows to use the Stokes feature.

Nicolas
[cfg-roms3d-stokes.xml.txt](https://github.com/user-attachments/files/16158818/cfg-roms3d-stokes.xml.txt)

**Comment by xzhou473** [comment]
Thank you so much!
