### ISSUE TITLE
simulation using GLORYS12V1 data

### ISSUE THREAD

**Issue by Motaeng** [ichthyop/ichthyop#105]
Dear Ichthyop community,

My apologies if this might be a simple question.

I would like to do simulations on Ichthyop using GLORYS12V1 data from CMEMS ( https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description ), in 3D. But I don't know which option I should use.

I am using version 3.3 of Ichthyop and the NEMO3D settings (figure below) to couple the data. I noticed that the NEMO3D settings of ichthyop request some specific files, such as:

HGR file pattern
ZGR file pattern
gridW file pattern

Is using the NEMO3D settings the best approach for GLORYS12V1 data and how can I find the files listed above or is it necessary to make some adaptation?

Thank you for any possible guidance.

Best regards,

Lucas

**Comment by Motaeng** [comment]
![Appendix 1](https://github.com/user-attachments/assets/b0907575-b058-43eb-9b24-e9dbc2fcb36a)

**Comment by barriern** [comment]
Hi Moateng. You closed the issue because you solved the problem?

**Comment by Motaeng** [comment]
Hi, @barriern. Yes i am closed the problem. I used other questions asked here to solve my problem [https://github.com/ichthyop/ichthyop/issues/81](url) and [https://github.com/ichthyop/ichthyop/issues/62](url)
