### ISSUE TITLE
inconsistency of few particles,  tagged 'recruited',  between "zone" and "recruited_zone" variables of the netcdf file

### ISSUE THREAD

**Issue by stephanepous** [ichthyop/ichthyop#11]
Hello,

Simulations with : 
dataset.nemo and natives mercator 3D inputs.
3d avection (euler) + h. dispersion
behavior : vertical migration only
8 release/recruitment zones ("from zone" and "in zone" choices) with 30000 particles
"stop moving when recruited" is "true"
transport duration : 250 days

When I calculated the total amount of recruited particles at the end of the simulation I found : 
--3019 recruited particles from "recruited_zone(end,:,:)" variable
--2877 recruited particles from "zone(end,:,2)" variable

I have checked a few particles not tagged "recruited" in the "zone" variable and they look like "recruited", i.e. no move after passing through a recruited zone.

Regards,
Stephane

**Comment by barriern** [comment]
Solved. Will be in next Ichthyop release.
