### ISSUE TITLE
Temperature tracking

### ISSUE THREAD

**Issue by smlombardo** [ichthyop/ichthyop#12]
My apologies if this is the incorrect location to ask what may be a simple question. I am currently trying to run a simulation using the GUI in Ichthyop 3.3.3. I am using NCOM data reformatted to the ROMS naming scheme for my hydrodynamic dataset (the workaround for HYCOM not being a supported data scheme). I am receiving an error while Previewing my simulation when "Variable Tracking" is toggled to "temperature" "salinity". The Preview view still properly displays.

My error is only with the "temperature" variable. There is no error for the "salinity" variable. Below is the error I receive:
_"ichthyop[warning] Error adding tracker temperature in NetCDF output file. The variable will not be recorded. | java.lang.IllegalArgumentException: Variable name (temperature) must be unique within Group"_ 

I have checked to make sure that my ocean data are formatted properly with the correct names, dimensions, datatype, and attributes. I cannot figure out what other tweaks I can try to remedy the error. Any assistance would be greatly appreciated.

**Comment by barriern** [comment]
Hi smlombardo.This is the right place. The error seems to be related to some NetCDF issues. Could you please try to run Ichthyop from the command line (either `cmd` if you are on Windows or `Terminal` if you are on Linux/Mac Os? It would help to find the exact location of the crash.
Thanks
Nicolas

**Comment by barriern** [comment]
And eventually please send me your configuration file.

**Comment by smlombardo** [comment]
Hi Nicolas,

Thank you for taking the time to address my problem. I greatly appreciate it. I do believe I have figured out my problem, though I will still provide you with the requested information (see attached).

In short, it appears that the error happens any time that "temperature" is toggled under "Output > Variable tracking", whether "temperature" is being tracked by another process (Lethal Temperature) or not. The only way to track temperature without an error is through the option under "Lethal Temperature > Track Temperature". I originally had temperature tracking toggled on under both Output and Lethal Temperature tabs.

[output_no_error.txt](https://github.com/ichthyop/ichthyop/files/6124221/output_no_error.txt)
[output_with_error.txt](https://github.com/ichthyop/ichthyop/files/6124225/output_with_error.txt)

[slombardo_Ichthyop.txt](https://github.com/ichthyop/ichthyop/files/6124232/slombardo_Ichthyop.txt)

.

**Comment by barriern** [comment]
Thanks for the update. I leave the issue opened and will try to have a look at it as soon as possible

**Comment by barriern** [comment]
issue solved

**Comment by TshikanaR** [comment]
Hello. I am new to the Ichthyop framework and please forgive me if the question I am about to ask has already been asked. I have  globcurrent velocities (in netcdf format) which I want to use to advect the virtual particles. I am not sure how to go about doing just that - please kindly assist me
