### ISSUE TITLE
vertical dispersion issue

### ISSUE THREAD

**Issue by gliu87** [ichthyop/ichthyop#13]
Hi,

I'm trying to run a test with vertical diffusion, however, it seems that there's no such an option in the new xml configuration file. So what should I do to include the diffusion effect into the particle tracking?

thanks
Leo

**Comment by barriern** [comment]
Hi gliu87. Could you please send me your configuration file? I will check that.

**Comment by gliu87** [comment]
Thanks for the quick reply. Here is the zip file for my configuration xml file, I generated it from the GUI application, and I didn't see any options for the vertical dispersion simulation.

[paramuricea_1kmaug_config_roms3d.zip](https://github.com/ichthyop/ichthyop/files/6128460/paramuricea_1kmaug_config_roms3d.zip)

**Comment by barriern** [comment]
I have slightly modified your configuration file to include the settings for vertical dispersion. Note that the `Kv` variable must be stored in the Dataset. 

Please let me know if you were able to run it, so that I can close the ticket.

**Comment by gliu87** [comment]
Thank you very much! It’s working.

best,
Leo

On Mar 16, 2021, at 04:56, Nicolas Barrier ***@***.***> wrote:

﻿

I have slightly modified your configuration file to include the settings for vertical dispersion. Note that the Kv variable must be stored in the Dataset.

Please let me know if you were able to run it, so that I can close the ticket.
