### ISSUE TITLE
ichthyop spatial intepolation

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#14]
Dear all, 
I am doing a methodological comparison between different Lagrangian tools.
I am trying to understand very precisely how ichthyop is interpolating MARS3D currents fields.
I read the documentation online, in the users manual and in Lett et al., and references and I cannot find, in detail, a mathematical description of how ichthyop interpolates currents. Could you please give me some more references or documentation about the spatial interpolation, more precisely following this doc. > http://documentation.ichthyop.org/faq.html#how-does-spatial-interpolation-work-in-ichthyop
Indeed for MARS3D, I observed that when the cell number decimale in which the particle is on x and y are inferior than 0.5, then the points which are used to make the interpolation are not those which surround this particle. I would like to understand it in more detail with more explanations or references if possible.

Thank you very much for your reply !

**Comment by barriern** [comment]
Hi Celine. There is no detailled documentation on how the code interpolates, except the one that you found. Ichthyop uses a simple bilinear interpolation, that's all. 

Regarding Mars3d, it is weird indeed. It may happen when the zonal cyclicity is activated, but usually this is the case only for global simulations.

Nicolas
