### ISSUE TITLE
Error during preview

### ISSUE THREAD

**Issue by MBendoni** [ichthyop/ichthyop#15]
Hi,

I am using icthyop-3.3.6 and I receive the following error when I try to preview the configuration of the model (using ROMS output):
`ichthyop[severe] Cannot invoke "ucar.nc2.Variable.read(int[], int[])" because the return value of "ucar.nc2.NetcdfFile.findVariable(String)" is null | java.lang.NullPointerException: Cannot invoke "ucar.nc2.Variable.read(int[], int[])" because the return value of "ucar.nc2.NetcdfFile.findVariable(String)" is null`

Any hint to fix it would be welcome.
I am sorry but I am not skilled in java language.

Thank you,
Michele

**Comment by MBendoni** [comment]
It was my mistake with assigning variable. Solved

**Comment by AFrouws** [comment]
> 
> 
> Hi,
> 
> I am using icthyop-3.3.6 and I receive the following error when I try to preview the configuration of the model (using ROMS output):
> `ichthyop[severe] Cannot invoke "ucar.nc2.Variable.read(int[], int[])" because the return value of "ucar.nc2.NetcdfFile.findVariable(String)" is null | java.lang.NullPointerException: Cannot invoke "ucar.nc2.Variable.read(int[], int[])" because the return value of "ucar.nc2.NetcdfFile.findVariable(String)" is null`
> 
> Any hint to fix it would be welcome.
> I am sorry but I am not skilled in java language.
> 
> Thank you,
> Michele


Hi Michelle,
I am receiving the same error, but am not sure if it is happening for the same reason. Could you clarify what you mean by "assigning variables within the configuration window", I hope that better understanding your solution might help me solve my issue as well. 
Thanks in advance,
Anna

**Comment by barriern** [comment]
Hi Anna. What version of Ichthtyop do you use? This bug was presumably solved in `3.3.7` if I remember well.
