### ISSUE TITLE
Growth error

### ISSUE THREAD

**Issue by DBerbue** [ichthyop/ichthyop#16]
Hi!

[Growth_test.zip](https://github.com/ichthyop/ichthyop/files/6246997/Growth_test.zip)
I'm trying to run a test using version 3.3.6 and getting this error message: java.lang.NullPointerException: Could not retrieve parameter action.growth/stage_tags | java.lang.InstantiationException: Failed to setup action Advanced/Biology/Growth.
I've been trying different coefficient values as tests, even tried to run a test with the predefined values but still getting that error. 
I must admit I'm not very skilled at java language, but I tried looking out the LinearGrowthAction jar file to find any clue about the error I'm getting, with no success.
Here's my code.

Thanks in advance!

Diana

**Comment by barriern** [comment]
Hi Diana. 

Some parameters are missing in your configuration file. I have added them in the enclosed file.

Nicolas
[Uploading Cozumel_corals_month_nbarrier.txt…]()

**Comment by DBerbue** [comment]
Hi Nicolas,

Thank you so much! 
I can't download the cfg file. Since yesterday it's still uploading.



Diana

**Comment by barriern** [comment]
Hi Diana. Sorry for my late response
[Cozumel_corals_month_nbarrier.txt](https://github.com/ichthyop/ichthyop/files/6341325/Cozumel_corals_month_nbarrier.txt)
Is it ok now?

**Comment by DBerbue** [comment]
Hi Nicolas,

Is working perfectly fine.

Thanks!

Diana
