### ISSUE TITLE
Missing NetCDF variables in a MARS3D dataset used by Ichthyop?

### ISSUE THREAD

**Issue by Miguel-com** [ichthyop/ichthyop#17]
Dear all,

My apologies if this may be a simple question. I am currently using the hydrodynamic dataset "mars-iroise.nc" located in the input folder of the 3.3.3 version of Ichthyop in order to assess a 3D simulation. However, I am wondering why the NetCDF variables "hc", "theta", and "b" are absent from this hydrodynamic dataset. According to the sample configuration file attached to this message, those variables are supposed to be present in the NetCDF file also attached to this message. Using these configuration and hydrodynamic files I can perform a simulation with no problems. Where does the model take the values of these variables from if it is not from the hydrodynamic files? What values does it take? How can I modify them?

Many thanks for any possible guidance,

Miguel

[mars-iroise.zip](https://github.com/ichthyop/ichthyop/files/6373705/mars-iroise.zip)
[2021_04_23_MiguelC_config_mars3d.txt](https://github.com/ichthyop/ichthyop/files/6373698/2021_04_23_MiguelC_config_mars3d.txt)

**Comment by barriern** [comment]
Hi Miguel

 Ichthyop finds out that these variables does not exist in the NetCDF, and thus assumes that simple sigma levels are used (V6 of Mars), not generalized ones (as in V8 of Mars).

Nicolas

**Comment by Miguel-com** [comment]
Hi Nicolas,

Thanks so much for your response.

Best,

Miguel
