### ISSUE TITLE
issues with preview of ROMS 3D Benguela template

### ISSUE THREAD

**Issue by AFrouws** [ichthyop/ichthyop#18]
Hi,
I have just installed Ichthyop and am using the ROMS 3D Bengula template to practice using the program for the first time. I ran in multiple errors when starting and had to adjust my input folder and the data notation (01 to 2001) for the input files to be read properly. I haven't changed any of the other parameters, saved my file after making changes, but am still running into an error (see complete output below). 
The error is as follows: 
ichthyop[severe] Cannot invoke "ucar.nc2.Attribute.getStringValue()" because "attrUnits" is null | java.lang.NullPointerException: Cannot invoke "ucar.nc2.Attribute.getStringValue()" because "attrUnits" is null

Does anyone have advice on what the error means and potential ways to tackle it?
Thank you in advance!

chthyop[info] [Configuration] Saved 2021_05_27_XXX_config_roms3d.xml
ichthyop[info] [Simulation] Initialising...
ichthyop[info] {Dataset} Open C:\Users\XXX\ichthyop-3.3.8\input\roms-benguela.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[severe] Cannot invoke "ucar.nc2.Attribute.getStringValue()" because "attrUnits" is null | java.lang.NullPointerException: Cannot invoke "ucar.nc2.Attribute.getStringValue()" because "attrUnits" is null
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)

**Comment by barriern** [comment]
Hi 

Sorry for my late response, I was on holidays. I see the problem. In the most recent version of Ichthyop, the management of time has been strongly modified. It now requires that the time variable of the NetCDF file has a `units` attribute. Which is missing in the template forcing files. I will try to correct it quickly.

Nicolas

**Comment by barriern** [comment]
Hi again

Could you please try by replacing the `roms-benguela.nc` file in the `input` folder by the one enclosed below? 

Thanks

Nicolas
[roms-benguela.zip](https://github.com/ichthyop/ichthyop/files/6575374/roms-benguela.zip)

**Comment by AFrouws** [comment]
Hi Nicolas,
Thank you for your swift reply. I don't get the previous error anymore but am currently receiving the following error: ichthyop[severe] [Dataset] Time value 3.1978368E9 (in seconds) not contained among NetCDF files. | java.lang.IndexOutOfBoundsException: [Dataset] Time value 3.1978368E9 (in seconds) not contained among NetCDF files.

Also, I am using version 3.3.8. I just downloaded it a few weeks ago. 
Regards,

Anna

**Comment by barriern** [comment]
Ok. So now you can just change the beginning time of the simulation (year 1900 month 05 day 03 at 00:00 seems to work for me)

Do you still have errors with the preview?

**Comment by AFrouws** [comment]
Hi Nicolas,
I have tried using the new file, and the time settings you suggested (1900) and unfortunately I still receive an error. My current error is: 

ichthyop[severe] Failed to create NetCDF output file ==> java.lang.UnsupportedOperationException: Couldn't load NetCDF C library (see log for details). | java.io.IOException: Failed to create NetCDF output file ==> java.lang.UnsupportedOperationException: Couldn't load NetCDF C library (see log for details).
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)

In addition, I was wondering if there is any documentation for Ichthyop with an explanation of different error terms and with information about the setup of input files (I am using ROMS data). 

Regards,

Anna

**Comment by barriern** [comment]
Hi Anna.

Ok , your error is quite normal. In the new Ichthyop versions, the NetCDF Java library has been updated. It requires an external C library (cf. http://documentation.ichthyop.org/start/download_nc.html)

Regarding your question, the documentation has been initiated but is far from complete.

Nicolas

**Comment by AFrouws** [comment]
Hi Nicolas,
Thank you for your help, it is finally running with the example files! 
I have another question: I am using data from a ROMS model managed by another research team. They would like to email you some questions about using qck files as input files because they were concerned about Ichthyop not correctly reading the coordinates. Is it possible for them to reach you by email with their specific questions? 

Regards,

Anna

**Comment by barriern** [comment]
Hi Anna. I close the issue then. You can tell your colleagues to submit a new issue. 

Cheers
