### ISSUE TITLE
compiler for old versions of ichthyop

### ISSUE THREAD

**Issue by jesskolbusz** [ichthyop/ichthyop#19]
I have version 3.3.3 and I wish to modify the source code and recompile it. 3.3.8 or 3.3.6 has too many changes from what I have been using currently. What is the best compiler to use for 3.3.3? 
Thanks!

**Comment by barriern** [comment]
Hi Jessica. 

You will need to download NetBeans. Open it, then click on `Open Project` and select the Ichthyop folder (you should see a coffee cup as icon). Then click on `Clean and Rebuild`

Nicolas
