### ISSUE TITLE
Vertical velocities in Ichthyop

### ISSUE THREAD

**Issue by Miguel-com** [ichthyop/ichthyop#20]
Dear Ichthyop community,

My apologies if these may be simple and general questions.

I am conducting some sensitivity tests of vertical advection in my study area by means of using different sigma levels to solve the hydrodynamic in a complex topography area. In this regard, I was wondering if it was possible to find further information about the equations used by Ichthyop to reconstruct the W velocity used to compute the vertical advection. Without success, I have tried to find the information in the source code of Ichthyop version 3.3.3.

On the other hand, I would like to perform other tests using the vertical velocities computed by the hydrodynamic model and stored in the corresponding hydrodynamic file. So, I would like to ask if someone could kindly share the code that should be added to the configuration files to use the W of the hydrodynamic model. I am using both the MARS and ROMS configuration files of version 3.3.3 attached to this message. I have seen that this issue was partially addressed in this Forum but unfortunately I am unable to download the configuration files adapted to this functionality located in this link: https://github.com/ichthyop/ichthyop/issues/3

I really appreciate any kind of help.

Best regards,

Miguel

[2021_06_17_MiguelC_config_roms3d.xml.txt](https://github.com/ichthyop/ichthyop/files/6671737/2021_06_17_MiguelC_config_roms3d.xml.txt)
[2021_06_17_MiguelC_config_mars3d.xml.txt](https://github.com/ichthyop/ichthyop/files/6671738/2021_06_17_MiguelC_config_mars3d.xml.txt)

**Comment by barriern** [comment]
Hi Miguel.

Sorry for the late response. 

The question of the computation of `W` fields is kind of a delicate subject. The equations are nowhere to be found, they can only be found in the code (`computeW` methods, for instance in [Mars3dCommon.java](https://github.com/ichthyop/ichthyop/blob/master/src/main/java/org/previmer/ichthyop/dataset/Mars3dCommon.java) or in [Roms3dCommon.java](https://github.com/ichthyop/ichthyop/blob/master/src/main/java/org/previmer/ichthyop/dataset/Roms3dCommon.java)). They have been implemented "with the flow". Besides, the reconstruction is not always good and may leed to unreastically huge vertical speeds, as discussed in #3 .

That is why we added the possibility to read the `W` field from an output fille. This feature exists for `Roms` **but not yet for Mars**. This can be activated by adding the following lines in the `Dataset` part of the configuration file (cf. enclosed file):

```
      <parameter>
        <key>read_var_w</key>
        <long_name>True if W should be read in files</long_name>
        <value>false</value>
        <default>false</default>
        <format>boolean</format>
        <description>True if W should be read in files</description>
      </parameter>
      <parameter>
        <key>field_var_w</key>
        <long_name>Name of the W variable</long_name>
        <value>vozocrtz</value>
        <default>vozocrtz</default>
        <description>Name of the W variable</description>
      </parameter>
```

However, the problem is that in `Roms`, W is saved on `T` points (center of the cells) while Ichthyop needs them on `W` points (edge of the cells). We therefore accept a half cell offset and assumes that W at the surface is 0.

It would be great if we could signficantly improve the computation of W, so if you have some leads just let us know.


Nicolas

**Comment by Miguel-com** [comment]
> Hi Miguel.
> 
> Sorry for the late response.
> 
> The question of the computation of `W` fields is kind of a delicate subject. The equations are nowhere to be found, they can only be found in the code (`computeW` methods, for instance in [Mars3dCommon.java](https://github.com/ichthyop/ichthyop/blob/master/src/main/java/org/previmer/ichthyop/dataset/Mars3dCommon.java) or in [Roms3dCommon.java](https://github.com/ichthyop/ichthyop/blob/master/src/main/java/org/previmer/ichthyop/dataset/Roms3dCommon.java)). They have been implemented "with the flow". Besides, the reconstruction is not always good and may leed to unreastically huge vertical speeds, as discussed in #3 .
> 
> That is why we added the possibility to read the `W` field from an output fille. This feature exists for `Roms` **but not yet for Mars**. This can be activated by adding the following lines in the `Dataset` part of the configuration file (cf. enclosed file):
> 
> ```
>       <parameter>
>         <key>read_var_w</key>
>         <long_name>True if W should be read in files</long_name>
>         <value>false</value>
>         <default>false</default>
>         <format>boolean</format>
>         <description>True if W should be read in files</description>
>       </parameter>
>       <parameter>
>         <key>field_var_w</key>
>         <long_name>Name of the W variable</long_name>
>         <value>vozocrtz</value>
>         <default>vozocrtz</default>
>         <description>Name of the W variable</description>
>       </parameter>
> ```
> 
> However, the problem is that in `Roms`, W is saved on `T` points (center of the cells) while Ichthyop needs them on `W` points (edge of the cells). We therefore accept a half cell offset and assumes that W at the surface is 0.
> 
> It would be great if we could signficantly improve the computation of W, so if you have some leads just let us know.
> 
> Nicolas

**Comment by Miguel-com** [comment]
Hi Nicholas,

Thanks for your detailed response. I will check carefully your kind comments and I will back to this issue.

Best regards,

Miguel

**Comment by Miguel-com** [comment]
> Hi Miguel.
> 
> Sorry for the late response.
> 
> The question of the computation of `W` fields is kind of a delicate subject. The equations are nowhere to be found, they can only be found in the code (`computeW` methods, for instance in [Mars3dCommon.java](https://github.com/ichthyop/ichthyop/blob/master/src/main/java/org/previmer/ichthyop/dataset/Mars3dCommon.java) or in [Roms3dCommon.java](https://github.com/ichthyop/ichthyop/blob/master/src/main/java/org/previmer/ichthyop/dataset/Roms3dCommon.java)). They have been implemented "with the flow". Besides, the reconstruction is not always good and may leed to unreastically huge vertical speeds, as discussed in #3 .
> 
> That is why we added the possibility to read the `W` field from an output fille. This feature exists for `Roms` **but not yet for Mars**. This can be activated by adding the following lines in the `Dataset` part of the configuration file (cf. enclosed file):
> 
> ```
>       <parameter>
>         <key>read_var_w</key>
>         <long_name>True if W should be read in files</long_name>
>         <value>false</value>
>         <default>false</default>
>         <format>boolean</format>
>         <description>True if W should be read in files</description>
>       </parameter>
>       <parameter>
>         <key>field_var_w</key>
>         <long_name>Name of the W variable</long_name>
>         <value>vozocrtz</value>
>         <default>vozocrtz</default>
>         <description>Name of the W variable</description>
>       </parameter>
> ```
> 
> However, the problem is that in `Roms`, W is saved on `T` points (center of the cells) while Ichthyop needs them on `W` points (edge of the cells). We therefore accept a half cell offset and assumes that W at the surface is 0.
> 
> It would be great if we could signficantly improve the computation of W, so if you have some leads just let us know.
> 
> Nicolas

Hi Nicolas,

I really appreciate your kind comments.

Since my hydrodynamic dataset W was absent, I computed the vertical advection through the Ichthyop method. In my firsts experiments, I noticed the huge W velocities that Ichthyop outputs in the simulation log. Next, I used different vertical resolutions in my hydrodynamic dataset and I was able to solve the W issue by using little stretching in the bottom levels of my sigma grid. I used an HYCOM model output interpolated from fixed depths to sigma depths. In my case, I think the problem comes from irrealistic low-velocity values near the bottom computed in the new interpolated grid that conducts to irrealistic horizontal gradients that affect the W computed by Ichthyop.

Best regards,

Miguel
