### ISSUE TITLE
An error occured while running ROMS 3D simulation

### ISSUE THREAD

**Issue by taoansf** [ichthyop/ichthyop#22]
Hello,

I'm trying to run a simulation using ROMS 3D forcing but without sucess.
The log shows this error message:

_(ichthyop) taoan@subae:/disco3/coralsol/taoan/ICHTHYOP$ java -jar /home/taoan/ichthyop-3.3.10/target/ichthyop-3.3.10-jar-with-dependencies.jar 2021_08_03_taoan_config_roms3d.xml
ichthyop[info] Opened configuration file /disco3/coralsol/taoan/ICHTHYOP/2021_08_03_taoan_config_roms3d.xml
ichthyop[info] ===== Simulation started =====
ichthyop[info] ++++ Run 1 / 1
ichthyop[info] Setting up...
ichthyop[info] {Dataset} Open /disco3/coralsol/taoan/ICHTHYOP/roms_ichthyop.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[info] Initializing...
ichthyop[severe] An error occured while running the simulation | java.lang.NullPointerException
  org.previmer.ichthyop.dataset.DatasetUtil.getDate(DatasetUtil.java:448)
  org.previmer.ichthyop.dataset.DatasetUtil.timeFirst(DatasetUtil.java:129)
  org.previmer.ichthyop.dataset.DatasetUtil.isTimeIntoFile(DatasetUtil.java:174)
  org.previmer.ichthyop.dataset.DatasetUtil.index(DatasetUtil.java:227)
  org.previmer.ichthyop.dataset.Roms3dDataset.setOnFirstTime(Roms3dDataset.java:137)
  org.previmer.ichthyop.dataset.RomsCommon.init(RomsCommon.java:198)
  org.previmer.ichthyop.dataset.Roms3dCommon.init(Roms3dCommon.java:59)
  org.previmer.ichthyop.manager.DatasetManager.initializePerformed(DatasetManager.java:118)
  org.previmer.ichthyop.manager.SimulationManager.fireInitializePerformed(SimulationManager.java:442)
  org.previmer.ichthyop.manager.SimulationManager.init(SimulationManager.java:390)
  org.previmer.ichthyop.IchthyopBatch.run(IchthyopBatch.java:93)
  java.base/java.lang.Thread.run(Thread.java:844)_

My simulation files can be downloaded here
https://drive.google.com/file/d/1g7su7owXIfmrX8wGFpDIZR6GnzZ_heBE/view?usp=sharing

Thanks for any help

With best regards

Taoan

**Comment by barriern** [comment]
Hi Taoan.

The problem is that you have set `scrum_time` as the time-variable. However, in your file, the time-variable is `ocean_time`. So you first need to correct your input file.

Still, the code won't run because the `ocean_time:units` attribute has the following value: `hours since 2014-11-01` while Ichthyop expects something like  `hours since 2014-11-01 00:00`. I have made a patch correction in the `develop` branch:

https://github.com/ichthyop/ichthyop/tree/develop

So you will need to download the code in this `develop` branch.

Nicolas

**Comment by taoansf** [comment]
Hello Nicolas,

I followed your instructions and it is working now

Thank you!
