### ISSUE TITLE
How to setup nested grid simulation

### ISSUE THREAD

**Issue by taoansf** [ichthyop/ichthyop#23]
Hello,

I'm looking for some instruction for how to setup a simulation using input data from nested grids.
I found that is possible to run ichthyop using multi input files by * file filter. However, I would like to know if it is possible to setup a simulation using nested grids with some priority criteria to select forcing grid.

Thanks for any help.

With best regards.

Taoan

**Comment by barriern** [comment]
Hi Taoan.

The use of nested grids is not available in Ichthyop. This is something that at some points we would like to implement.

The `*` filters allows to include multiple input files from the same grid. For instance, if you have 10 years of monthly files, it allows to read the 10 files. 

Nicolas
