### ISSUE TITLE
ERROR: [Simulation] Initialisation failed (performing: SETUP)

### ISSUE THREAD

**Issue by cuchisavila** [ichthyop/ichthyop#25]
Hi 
I just installed  ichthyop 3.3.10 and was trying to do a test run , but I am getting an error.
When i hit preview or run simulations I get the error 

This is the text when I started the preview:
ichthyop[info] [Simulation] Initialising...
ichthyop[severe] [Dataset] D:\ichthyop\target\input is not a valid directory. | java.io.IOException: [Dataset] D:\ichthyop\target\input is not a valid directory.
ichthyop[severe] [Simulation] Initialisation failed (performing: SETUP)

Did I not install ichthyop correctly? What does this error mean and how can I fix it?
Scr

I am attaching a doc with screen shots since I was not able to copy pictures diretly
[Ichtyop error screen shot.docx](https://github.com/ichthyop/ichthyop/files/7213005/Ichtyop.error.screen.shot.docx)

 

 '

**Comment by barriern** [comment]
Hi

I think is due to the fact that you are running Ichthyop fro the `target` folder. The `input` folder is in the parent directory. What you can do is move the `jar` files into the root folder and it should work.

Or you can run it from the root folder as follows:
```
java -jar target/ichthyop_3.3.8.jar
```

**Comment by cuchisavila** [comment]
Ok, I moved it, but I downloaded the files nd it put itself in that target folder by it self :(
I now I have a new error
ichthyop[info] Ichthyop 3.3.10 - Welcome on board !
ichthyop[info] [Configuration] Opened D:\ichthyop\target\cfg\2021_09_23_Alex_config_roms3d.xml
ichthyop[info] [Configuration] {New} Created file D:\ichthyop\cfg\2021_09_23_Alex_config_roms3d.xml
ichthyop[info] [Configuration] Opened D:\ichthyop\cfg\2021_09_23_Alex_config_roms3d.xml
ichthyop[info] [Simulation] Initialising...
ichthyop[info] {Dataset} Open D:\ichthyop\input\roms-benguela.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[info] {Dataset} Open D:\ichthyop\input\roms-benguela.nc
ichthyop[info] Reading NetCDF variables...
ichthyop[info] Release manager initialization [OK]
ichthyop[info] Time manager initialization [OK]
ichthyop[info] Zone manager initialization [OK]
ichthyop[severe] Failed to create NetCDF output file ==> java.lang.UnsupportedOperationException: Couldn't load NetCDF C library (see log for details). | java.io.IOException: Failed to create NetCDF output file ==> java.lang.UnsupportedOperationException: Couldn't load NetCDF C library (see log for details).
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)

**Comment by barriern** [comment]
Hi.

This is because you need to install NetCDF-C library, as indicated in the error message.

You can find it here:

https://www.unidata.ucar.edu/downloads/netcdf/

Nicolas

**Comment by cuchisavila** [comment]
Hi Nicholas
I did download the NetCDF library at the same time I downloaded icthyop. the NetCDF library is there, but I still get that error. I also added the path to this library too. Im assuming it might be something as simple as it isn't in the right folder.
Currently my icthyop path is:
D:\ichthyop\ichthyop-3.3.10-jar-with-dependencies.jar
Currently my NCFD library path is:
C:\Program Files\netCDF 4.8.0
Do i need to move it somewhere else?


Also I notices that in the program, the example files its referencing does not match the path
for example: for the zone-benguela.xml file
the preset in recruitment is D:\ichthyop\cfg\benguela_zones.xml
but there are no files there
the actual file is located in :
D:\ichthyop\target\classes\templates
But i did not move this location, when I downloaded it it came like this

**Comment by barriern** [comment]
Hi 
This is weird because the error is really due to a missing library. When you open a Cmd invite, and you type `ncdump`, what message do you have? 

Regarding the path of `xml` files, Ichthyop will copy them from the `template` folder into the `cfg` one.

Nicolas

**Comment by cuchisavila** [comment]
Hi Nicolas
I tried using Git CMD and typed ncdump, and got: 'ncdump' is not recognized as an internal or external command, operable program or batch file. 
I also tried using Git bash and typed ncdump and got : bash: ncdump: command not found

**Comment by barriern** [comment]
Hi

The message that you have is likely due to the fact that NetCDF-C is not found, which likely causes the errror in Ichthyop. You might need to add the NetCDF bin folder into your PATH, as indicated in https://pjbartlein.github.io/REarthSysSci/install_netCDF.html
