### ISSUE TITLE
backward mod and buoyancy

### ISSUE THREAD

**Issue by jfleroux** [ichthyop/ichthyop#26]
Hi,

I try to simulate the inverse surface float drift from the MARS3D model.
I have set a very low density but yet during the reverse drift the particles dive.
Have I made a mistake?
Below is an extract of the parameters 
		:action.buoyancy.enabled = "true" ;
		:action.buoyancy.particle_density = "0.1" ;
		:action.buoyancy.density_file = "" ;
		:action.buoyancy.age_max = "0.0" ;
		:action.buoyancy.salinity_field = "SAL" ;
		:action.buoyancy.temperature_field = "TEMP" ;
		:action.hdisp.enabled = "false" ;
		:release.txtfile.enabled = "false" ;
		:release.ncfile.enabled = "false" ;
		:release.zone.enabled = "false" ;
		:release.patches.enabled = "false" ;
		:release.stain.enabled = "true" ;
		:release.stain.number_particles = "100" ;
		:release.stain.lon_stain = "-5.16" ;
		:release.stain.lat_stain = "51.86" ;
		:release.stain.depth_stain = "0.0" ;
		:release.stain.radius_stain = "100.0" ;
		:release.stain.thickness_stain = "1.0" ;

and the depth values at the end after 23 days (at the beginning they are less than 0.5 )
 depth =
  -36.11556, -48.9006, -37.17772, -16.86766, -13.80213, -4.557264, -5.983146, 
    -52.12046, -16.25679, -25.33077, -35.54165, -35.23041, -51.27585, 
    -8.629692, -19.01681, -16.67158, -3.048606, -22.25202, -19.04533, 
    -59.16073, -31.27066, -23.94583, -24.88975, -11.05154, -21.09366, 
    -8.391805, -31.32644, -7.203243, -33.36157, -38.78206, -3.161202, 
    -44.48134, -23.13779, -10.06503, -13.12144, -47.7611, -15.29474, 
    -35.97757, -38.23178, -45.74821, -17.22677, -3.698554, -48.99436, 
    -23.10014, -23.60997, -12.6711, -16.35638, -31.70296, -30.15268, 
    -30.04577, -28.5314, -34.79932, -13.9342, -10.66266, -33.58184, 
    -46.68512, -18.74609, -15.04118, -49.1451, -7.696893, -44.22253, 
    -9.987008, -8.4168, -14.74735, -5.864066, -38.41117, -40.85021, 
    -30.68596, -27.36484, -32.20163, -15.20696, -48.44061, -11.91816, 
    -19.97751, -13.95782, -41.84369, -34.12119, -34.55555, -41.85208, 
    -17.65693, -9.065445, -13.61514, -12.77234, -11.48472, -14.12845, 
    -13.56955, -27.04205, -18.21748, -30.87831, -11.07296, -12.99358, 
    -39.84177, -36.5855, -3.144675, -9.469021, -33.23525, -27.52017, 
    -40.70393, -32.62604, -2.841038 ;

Best regards,
Jean-François

**Comment by jfleroux** [comment]
Hi,

I had deactivate the buoyancy process but I have the same result, depth of the particles grow in backward mod.

Jean-François

**Comment by barriern** [comment]
Hi Jean-Francois.
Could you please send me your configuration files and some forcing files, so that I can try to see what is going on?
Thanks
Nicolas

**Comment by barriern** [comment]
Hi Jean-Francois.
I am not sure you ever sent me the configuration files, so that I can have a look at the issue?
Nicolas
