### ISSUE TITLE
java.time.format.DateTimeParseException: text ** could not be parsed at index 5

### ISSUE THREAD

**Issue by masdehade** [ichthyop/ichthyop#27]
Hi 
I just installed  ichthyop 3.3.8 and use openjdk 11 was trying to run simulation, but I am getting an error.
When i hit preview or run simulations I get the error.

ichthyop[info] [Simulation] Initialising...
ichthyop[info] {Dataset} Open /home/hade/ichthyop-3.3.8/input/roms-sangiang.nc
ichthyop[info] Release manager setup [OK]
ichthyop[severe] Text 'year 01 month 01 day 06 at 19:00' could not be parsed at index 5 | java.time.format.DateTimeParseException: Text 'year 01 month 01 day 06 at 19:00' could not be parsed at index 5
  java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
  java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
  java.base/java.time.LocalDateTime.parse(LocalDateTime.java:492)
  org.previmer.ichthyop.manager.TimeManager.loadParameters(TimeManager.java:161)
  org.previmer.ichthyop.manager.TimeManager.setupPerformed(TimeManager.java:382)
  org.previmer.ichthyop.manager.SimulationManager.fireSetupPerformed(SimulationManager.java:426)
  org.previmer.ichthyop.manager.SimulationManager.setup(SimulationManager.java:381)
  org.previmer.ichthyop.ui.IchthyopView$SimulationPreviewTask.doInBackground(IchthyopView.java:593)
  java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  java.base/java.lang.Thread.run(Thread.java:829)
ichthyop[severe] [Simulation] Initialisation failed (performing: SETUP)

anyone can help me?

**Comment by barriern** [comment]
Hi,
Ichthyop expects a date format as follows:

```
year 0001 month 01 day 06 at 19:00
```

with a 4-digit number of the year.

Nicolas

**Comment by oceandiscovery** [comment]
Hello:

I am trying to run ICHTHYOP v.3.3.12 on a computer with the following characteristics:
- Java: 16.0.1; Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24
- Runtime: Java(TM) SE Runtime Environment 16.0.1+9-24
- System: Mac OS X version 11.4 running on x86_64; UTF-8; en_GB (nb)

However, I'm getting an error message that I find strange:

> ichthyop[severe] Text '1990 mon h 01 day 01 a 00:00:00' could not be parsed at index 4 | java.time.format.DateTimeParseException: Text '1990 mon h 01 day 01 a 00:00:00' could not be parsed at index 4

Please note that the year format is four digits, the month format is two digits, the day format is two digits, etc., but also note that the message shows a problem with the letter "t".

Thank you very much.

Andrés

The complete error message is as follows:
```
--- exec-maven-plugin:3.0.0:exec (default-cli) @ ichthyop ---
ichthyop[info] Ichthyop 3.3.12 - Welcome on board !
ichthyop[info] [Configuration] Opened /Users/aospina/NetBeansProjects/A0_INPESCA_CFG/ichthyop_v3312_testing.xml
ichthyop[info] [Simulation] Initialising...
ichthyop[info] {Dataset} Open /Users/aospina/NetBeansProjects/A1_INPESCA_INPUT/new_cut2_roms_his_Y2000M8_test.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated action "Advanced/Transport/Horizontal dispersion"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[severe] Text '1990 mon h 01 day 01 a  00:00' could not be parsed at index 4 | java.time.format.DateTimeParseException: Text '1990 mon h 01 day 01 a  00:00' could not be parsed at index 4
  java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
  java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
  java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
  org.previmer.ichthyop.dataset.DatasetUtil.getDateUnit(DatasetUtil.java:573)
  org.previmer.ichthyop.dataset.DatasetUtil.getDateLeap(DatasetUtil.java:478)
  org.previmer.ichthyop.dataset.DatasetUtil.getDate(DatasetUtil.java:467)
  org.previmer.ichthyop.dataset.DatasetUtil.getDate(DatasetUtil.java:459)
  org.previmer.ichthyop.dataset.DatasetUtil.timeFirst(DatasetUtil.java:135)
  org.previmer.ichthyop.dataset.DatasetUtil.isTimeIntoFile(DatasetUtil.java:180)
  org.previmer.ichthyop.dataset.DatasetUtil.index(DatasetUtil.java:233)
  org.previmer.ichthyop.dataset.Roms3dDataset.setOnFirstTime(Roms3dDataset.java:137)
  org.previmer.ichthyop.dataset.RomsCommon.init(RomsCommon.java:198)
  org.previmer.ichthyop.dataset.Roms3dCommon.init(Roms3dCommon.java:59)
  org.previmer.ichthyop.manager.DatasetManager.initializePerformed(DatasetManager.java:118)
  org.previmer.ichthyop.manager.SimulationManager.fireInitializePerformed(SimulationManager.java:442)
  org.previmer.ichthyop.manager.SimulationManager.init(SimulationManager.java:390)
  org.previmer.ichthyop.ui.IchthyopView$SimulationPreviewTask.doInBackground(IchthyopView.java:595)
  java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base/java.lang.Thread.run(Thread.java:831)
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)
```

**Comment by barriern** [comment]
Hi Andres. Could you please send me your XML configuration file? Thanks

**Comment by oceandiscovery** [comment]
Hi, sure. I'm posting the xml file here. Please change the extension to xml again, I have put txt temporarily because github does not allow to upload files in xml format.
Cheers!


[](url
[ichthyop_v3312_testing.xml.txt](https://github.com/ichthyop/ichthyop/files/9195896/ichthyop_v3312_testing.xml.txt)
)

**Comment by barriern** [comment]
Ok I think I see the problem. The nature of the `time_of_origin` parameter has changed. Now, it contains the time units in the NetCDF file, following the NetCDF conventions.

If the `time:units` attribute is found in the NetCDF file, the `time_of_origin` parameter is ignored. If this attribute is missing, then the units must me providing following the following formats:

```
seconds since 1990-01-01 00:00:00
```

You can eventually replace seconds by days. The choice depends on your file.

So try replacing `time_of_origin` parameter by the above

Nicolas

**Comment by barriern** [comment]
You just need to modify the value of the parameter.

**Comment by oceandiscovery** [comment]
Hello Nicolas:

Understood, but it is counter-intuitive when you are using the graphical console and the system warns you that the format should be "year YYYY month MM day dd at HH:MM".

I attach an example image.

Thank you
<img width="1439" alt="Screenshot 2022-07-27 at 14 53 43" src="https://user-images.githubusercontent.com/56823311/181251803-cd3d485c-492f-4e24-b16a-1e5dd08cd137.png">
.

**Comment by barriern** [comment]
Yeah sure I agree. The reason is because in your XML file, the format of this parameter is set to `date`. In the enclosed XML file, the format constrain has been removed so you will not have the error message anymore
[ichthyop_v3312_testing.xml.corr.txt](https://github.com/ichthyop/ichthyop/files/9199041/ichthyop_v3312_testing.xml.corr.txt)
.
