### ISSUE TITLE
The temperature used by Ichthyop

### ISSUE THREAD

**Issue by Miguel-com** [ichthyop/ichthyop#29]
Dear Ichthyop community,

My apologies if this might be a simple question.

I was wondering what kind of temperature should be present in the hydrodynamic dataset. In-situ temperature or potential temperature? I am working with a 3d grid that contains in-situ temperature.

Thanks for any possible guidance.

Best regards,

Miguel

**Comment by barriern** [comment]
Hi.

Ichthyop assumes that potential temperature is used when it is used in the calculation of particle movements due to buoyancy (BuoyancyAction.java). 

Otherwise, if you don't use this specific process, you can use in-situ temperature (if T is used in the growth process for instance).

Nicolas
