### ISSUE TITLE
Fail to read dataset time dimension

### ISSUE THREAD

**Issue by cuchisavila** [ichthyop/ichthyop#35]
I keep on getting this same error. I have tried changing the time under time parameters. They seem to match what is inside the .nc file, but still I get these error. What does it mean and how do I fix it?

**Comment by barriern** [comment]
Hi 

I assume that you properly set the time dimension parameter? Depending on the datasets, it can be `time`, `time_counter`, `ocean_time` or even `t`. 

If so, could you please send me the snapshot of the time variable and the configuration file?

Nicolas

**Comment by cuchisavila** [comment]
![image](https://user-images.githubusercontent.com/39143475/152437790-b3a6dc91-5614-4589-9c4a-e6b78c2595bf.png)
![image](https://user-images.githubusercontent.com/39143475/152437894-3f8cd63c-80dd-4411-8354-394e70245c52.png)
is this what you mean by configuration file?
I have tried with and with out a grid file and still get the same error
![image](https://user-images.githubusercontent.com/39143475/152438127-26fd7e35-533d-47b3-80ee-03058e859ea7.png)

**Comment by barriern** [comment]
No, this is not exactly what I need. I meant the name of the dimension in the NetCDF file. You can check it using the R library `ncdf4` for instance. If you can't, please send me your forcing file I will have a look at it.

**Comment by cuchisavila** [comment]
This is one of the many roms files i have and need to be able to run
nc_open('ocean_his_4012.nc')
File ocean_his_4012.nc (NC_FORMAT_64BIT):

     85 variables (excluding dimension variables):
        int ntimes[]   
            long_name: number of long time-steps
        int ndtfast[]   
            long_name: number of short time-steps
        double dt[]   
            long_name: size of long time-steps
            units: second
        double dtfast[]   
            long_name: size of short time-steps
            units: second
        double dstart[]   
            long_name: time stamp assigned to model initilization
            units: days since 2005-01-01 00:00:00
        int nHIS[]   
            long_name: number of time-steps between history records
        int ndefHIS[]   
            long_name: number of time-steps between the creation of history files
        int nRST[]   
            long_name: number of time-steps between restart records
        int ntsAVG[]   
            long_name: starting time-step for accumulation of time-averaged fields
        int nAVG[]   
            long_name: number of time-steps between time-averaged records
        int ndefAVG[]   
            long_name: number of time-steps between the creation of average files
        double Falpha[]   
            long_name: Power-law shape barotropic filter parameter
        double Fbeta[]   
            long_name: Power-law shape barotropic filter parameter
        double Fgamma[]   
            long_name: Power-law shape barotropic filter parameter
        double nl_tnu2[tracer]   
            long_name: nonlinear model Laplacian mixing coefficient for tracers
            units: meter2 second-1
        double nl_visc2[]   
            long_name: nonlinear model Laplacian mixing coefficient for momentum
            units: meter2 second-1
        double Akt_bak[tracer]   
            long_name: background vertical mixing coefficient for tracers
            units: meter2 second-1
        double Akv_bak[]   
            long_name: background vertical mixing coefficient for momentum
            units: meter2 second-1
        double Akk_bak[]   
            long_name: background vertical mixing coefficient for turbulent energy
            units: meter2 second-1
        double Akp_bak[]   
            long_name: background vertical mixing coefficient for length scale
            units: meter2 second-1
        double rdrg[]   
            long_name: linear drag coefficient
            units: meter second-1
        double rdrg2[]   
            long_name: quadratic drag coefficient
        double Zob[]   
            long_name: bottom roughness
            units: meter
        double Zos[]   
            long_name: surface roughness
            units: meter
        double Znudg[]   
            long_name: free-surface nudging/relaxation inverse time scale
            units: day-1
        double M2nudg[]   
            long_name: 2D momentum nudging/relaxation inverse time scale
            units: day-1
        double M3nudg[]   
            long_name: 3D momentum nudging/relaxation inverse time scale
            units: day-1
        double Tnudg[tracer]   
            long_name: Tracers nudging/relaxation inverse time scale
            units: day-1
        double FSobc_in[boundary]   
            long_name: free-surface inflow, nudging inverse time scale
            units: second-1
        double FSobc_out[boundary]   
            long_name: free-surface outflow, nudging inverse time scale
            units: second-1
        double M2obc_in[boundary]   
            long_name: 2D momentum inflow, nudging inverse time scale
            units: second-1
        double M2obc_out[boundary]   
            long_name: 2D momentum outflow, nudging inverse time scale
            units: second-1
        double Tobc_in[tracer,boundary]   
            long_name: tracers inflow, nudging inverse time scale
            units: second-1
        double Tobc_out[tracer,boundary]   
            long_name: tracers outflow, nudging inverse time scale
            units: second-1
        double M3obc_in[boundary]   
            long_name: 3D momentum inflow, nudging inverse time scale
            units: second-1
        double M3obc_out[boundary]   
            long_name: 3D momentum outflow, nudging inverse time scale
            units: second-1
        double rho0[]   
            long_name: mean density used in Boussinesq approximation
            units: kilogram meter-3
        double gamma2[]   
            long_name: slipperiness parameter
        int LtracerSrc[tracer]   
            long_name: tracer point sources and sink activation switch
            flag_values: 0
             flag_values: 1
            flag_meanings: .FALSE. .TRUE.
        int spherical[]   
            long_name: grid type logical switch
            flag_values: 0
             flag_values: 1
            flag_meanings: Cartesian spherical
        double xl[]   
            long_name: domain length in the XI-direction
            units: meter
        double el[]   
            long_name: domain length in the ETA-direction
            units: meter
        int Vtransform[]   
            long_name: vertical terrain-following transformation equation
        int Vstretching[]   
            long_name: vertical terrain-following stretching function
        double theta_s[]   
            long_name: S-coordinate surface control parameter
        double theta_b[]   
            long_name: S-coordinate bottom control parameter
        double Tcline[]   
            long_name: S-coordinate surface/bottom layer width
            units: meter
        double hc[]   
            long_name: S-coordinate parameter, critical depth
            units: meter
        double Cs_r[s_rho]   
            long_name: S-coordinate stretching curves at RHO-points
            valid_min: -1
            valid_max: 0
            field: Cs_r, scalar
        double Cs_w[s_w]   
            long_name: S-coordinate stretching curves at W-points
            valid_min: -1
            valid_max: 0
            field: Cs_w, scalar
        double user[Nuser]   
            long_name: user generic parameters
            field: user, scalar
        double h[xi_rho,eta_rho]   
            long_name: bathymetry at RHO-points
            units: meter
            coordinates: lon_rho lat_rho
            field: bath, scalar
        double f[xi_rho,eta_rho]   
            long_name: Coriolis parameter at RHO-points
            units: second-1
            coordinates: lon_rho lat_rho
            field: coriolis, scalar
        double pm[xi_rho,eta_rho]   
            long_name: curvilinear coordinate metric in XI
            units: meter-1
            coordinates: lon_rho lat_rho
            field: pm, scalar
        double pn[xi_rho,eta_rho]   
            long_name: curvilinear coordinate metric in ETA
            units: meter-1
            coordinates: lon_rho lat_rho
            field: pn, scalar
        double lon_rho[xi_rho,eta_rho]   
            long_name: longitude of RHO-points
            units: degree_east
            standard_name: longitude
            field: lon_rho, scalar
        double lat_rho[xi_rho,eta_rho]   
            long_name: latitude of RHO-points
            units: degree_north
            standard_name: latitude
            field: lat_rho, scalar
        double lon_u[xi_u,eta_u]   
            long_name: longitude of U-points
            units: degree_east
            standard_name: longitude
            field: lon_u, scalar
        double lat_u[xi_u,eta_u]   
            long_name: latitude of U-points
            units: degree_north
            standard_name: latitude
            field: lat_u, scalar
        double lon_v[xi_v,eta_v]   
            long_name: longitude of V-points
            units: degree_east
            standard_name: longitude
            field: lon_v, scalar
        double lat_v[xi_v,eta_v]   
            long_name: latitude of V-points
            units: degree_north
            standard_name: latitude
            field: lat_v, scalar
        double lon_psi[xi_psi,eta_psi]   
            long_name: longitude of PSI-points
            units: degree_east
            standard_name: longitude
            field: lon_psi, scalar
        double lat_psi[xi_psi,eta_psi]   
            long_name: latitude of PSI-points
            units: degree_north
            standard_name: latitude
            field: lat_psi, scalar
        double angle[xi_rho,eta_rho]   
            long_name: angle between XI-axis and EAST
            units: radians
            coordinates: lon_rho lat_rho
            field: angle, scalar
        double mask_rho[xi_rho,eta_rho]   
            long_name: mask on RHO-points
            flag_values: 0
             flag_values: 1
            flag_meanings: land water
            coordinates: lon_rho lat_rho
        double mask_u[xi_u,eta_u]   
            long_name: mask on U-points
            flag_values: 0
             flag_values: 1
            flag_meanings: land water
            coordinates: lon_u lat_u
        double mask_v[xi_v,eta_v]   
            long_name: mask on V-points
            flag_values: 0
             flag_values: 1
            flag_meanings: land water
            coordinates: lon_v lat_v
        double mask_psi[xi_psi,eta_psi]   
            long_name: mask on psi-points
            flag_values: 0
             flag_values: 1
            flag_meanings: land water
            coordinates: lon_psi lat_psi
        float zeta[xi_rho,eta_rho,ocean_time]   
            long_name: free-surface
            units: meter
            time: ocean_time
            coordinates: lon_rho lat_rho ocean_time
            field: free-surface, scalar, series
            _FillValue: 9.99999993381581e+36
        float ubar[xi_u,eta_u,ocean_time]   
            long_name: vertically integrated u-momentum component
            units: meter second-1
            time: ocean_time
            coordinates: lon_u lat_u ocean_time
            field: ubar-velocity, scalar, series
            _FillValue: 9.99999993381581e+36
        float vbar[xi_v,eta_v,ocean_time]   
            long_name: vertically integrated v-momentum component
            units: meter second-1
            time: ocean_time
            coordinates: lon_v lat_v ocean_time
            field: vbar-velocity, scalar, series
            _FillValue: 9.99999993381581e+36
        float u[xi_u,eta_u,s_rho,ocean_time]   
            long_name: u-momentum component
            units: meter second-1
            time: ocean_time
            coordinates: lon_u lat_u s_rho ocean_time
            field: u-velocity, scalar, series
            _FillValue: 9.99999993381581e+36
        float v[xi_v,eta_v,s_rho,ocean_time]   
            long_name: v-momentum component
            units: meter second-1
            time: ocean_time
            coordinates: lon_v lat_v s_rho ocean_time
            field: v-velocity, scalar, series
            _FillValue: 9.99999993381581e+36
        float w[xi_rho,eta_rho,s_w,ocean_time]   
            long_name: vertical momentum component
            units: meter second-1
            time: ocean_time
            coordinates: lon_rho lat_rho s_w ocean_time
            field: w-velocity, scalar, series
            _FillValue: 9.99999993381581e+36
        float temp[xi_rho,eta_rho,s_rho,ocean_time]   
            long_name: potential temperature
            units: Celsius
            time: ocean_time
            coordinates: lon_rho lat_rho s_rho ocean_time
            field: temperature, scalar, series
            _FillValue: 9.99999993381581e+36
        float salt[xi_rho,eta_rho,s_rho,ocean_time]   
            long_name: salinity
            time: ocean_time
            coordinates: lon_rho lat_rho s_rho ocean_time
            field: salinity, scalar, series
            _FillValue: 9.99999993381581e+36
        float AKv[xi_rho,eta_rho,s_w,ocean_time]   
            long_name: vertical viscosity coefficient
            units: meter2 second-1
            time: ocean_time
            coordinates: lon_rho lat_rho s_w ocean_time
            field: AKv, scalar, series
        float AKt[xi_rho,eta_rho,s_w,ocean_time]   
            long_name: temperature vertical diffusion coefficient
            units: meter2 second-1
            time: ocean_time
            coordinates: lon_rho lat_rho s_w ocean_time
            field: AKt, scalar, series
        float AKs[xi_rho,eta_rho,s_w,ocean_time]   
            long_name: salinity vertical diffusion coefficient
            units: meter2 second-1
            time: ocean_time
            coordinates: lon_rho lat_rho s_w ocean_time
            field: AKs, scalar, series
        float tke[xi_rho,eta_rho,s_w,ocean_time]   
            long_name: turbulent kinetic energy
            units: meter2 second-2
            time: ocean_time
            coordinates: lon_rho lat_rho s_w ocean_time
            field: tke, scalar, series
        float shflux[xi_rho,eta_rho,ocean_time]   
            long_name: surface net heat flux
            units: watt meter-2
            negative_value: upward flux, cooling
            positive_value: downward flux, heating
            time: ocean_time
            coordinates: lon_rho lat_rho ocean_time
            field: surface heat flux, scalar, series
            _FillValue: 9.99999993381581e+36
        float latent[xi_rho,eta_rho,ocean_time]   
            long_name: net latent heat flux
            units: watt meter-2
            negative_value: upward flux, cooling
            positive_value: downward flux, heating
            time: ocean_time
            coordinates: lon_rho lat_rho ocean_time
            field: latent heat flux, scalar, series
            _FillValue: 9.99999993381581e+36
        float sensible[xi_rho,eta_rho,ocean_time]   
            long_name: net sensible heat flux
            units: watt meter-2
            negative_value: upward flux, cooling
            positive_value: downward flux, heating
            time: ocean_time
            coordinates: lon_rho lat_rho ocean_time
            field: sensible heat flux, scalar, series
            _FillValue: 9.99999993381581e+36
        float lwrad[xi_rho,eta_rho,ocean_time]   
            long_name: net longwave radiation flux
            units: watt meter-2
            negative_value: upward flux, cooling
            positive_value: downward flux, heating
            time: ocean_time
            coordinates: lon_rho lat_rho ocean_time
            field: longwave radiation, scalar, series
            _FillValue: 9.99999993381581e+36
        float swrad[xi_rho,eta_rho,ocean_time]   
            long_name: solar shortwave radiation flux
            units: watt meter-2
            negative_value: upward flux, cooling
            positive_value: downward flux, heating
            time: ocean_time
            coordinates: lon_rho lat_rho ocean_time
            field: shortwave radiation, scalar, series
            _FillValue: 9.99999993381581e+36

     15 dimensions:
        xi_rho  Size:310 (no dimvar)
        xi_u  Size:309 (no dimvar)
        xi_v  Size:310 (no dimvar)
        xi_psi  Size:309 (no dimvar)
        eta_rho  Size:522 (no dimvar)
        eta_u  Size:522 (no dimvar)
        eta_v  Size:521 (no dimvar)
        eta_psi  Size:521 (no dimvar)
        N  Size:40 (no dimvar)
        s_rho  Size:40 
            long_name: S-coordinate at RHO-points
            valid_min: -1
            valid_max: 0
            positive: up
            standard_name: ocean_s_coordinate_g2
            formula_terms: s: s_rho C: Cs_r eta: zeta depth: h depth_c: hc
            field: s_rho, scalar
        s_w  Size:41 
            long_name: S-coordinate at W-points
            valid_min: -1
            valid_max: 0
            positive: up
            standard_name: ocean_s_coordinate_g2
            formula_terms: s: s_w C: Cs_w eta: zeta depth: h depth_c: hc
            field: s_w, scalar
        tracer  Size:2 (no dimvar)
        boundary  Size:4 (no dimvar)
        ocean_time  Size:6   *** is unlimited *** 
            long_name: time since initialization
            units: seconds since 2005-01-01 00:00:00
            calendar: gregorian
            field: time, scalar, series
        Nuser  Size:25 (no dimvar)

    36 global attributes:
        file: ocean_his_4012.nc
        format: netCDF-3 64bit offset file
        Conventions: CF-1.4
        type: ROMS/TOMS history file
        title: Domain 41-50N, CR, CONST_ATTENUATION_AK
        rst_file: ocean_rst.nc
        his_base: ocean_his
        avg_file: ocean_avg.nc
        grd_file: /home/aruba/vol1/serofeev/OW/Prm/grd_ow2km_03_smooth04_new.nc
        ini_file: ocean_rst_y.nc
        frc_file_01: /home/aruba/vol1/serofeev/OW/Prm/frc_wind_var.nc
        frc_file_02: /home/aruba/vol1/serofeev/OW/Prm//frc_ow2km_Swrad.nc
        frc_file_03: /home/aruba/vol1/serofeev/OW/Prm/frc_ow2km_Tair.nc
        frc_file_04: /home/aruba/vol1/serofeev/OW/Prm/frc_ow2km_Pair.nc
        frc_file_05: /home/aruba/vol1/serofeev/OW/Prm/frc_ow2km_Qair.nc
        frc_file_06: /home/aruba/vol1/serofeev/OW/Prm/frc_ow2km_Cloud.nc
        frc_file_07: /home/aruba/vol1/serofeev/OW/Prm/ow2km_CR.nc
        frc_file_08: /home/aruba/vol1/serofeev/OW/Prm/rivers_2014-2016.nc
        frc_file_09: /home/aruba/vol1/serofeev/OW/Prm/ow2km_tide.nc
        bry_file: /home/aruba/vol1/serofeev/OW/Prm/orw2km_bc_hycom.nc
        script_file: ocean1.in
        NLM_LBC: 
EDGE:  WEST   SOUTH  EAST   NORTH  
zeta:  Cha    Cha    Clo    Cha    
ubar:  Fla    Fla    Clo    Fla    
vbar:  Fla    Fla    Clo    Fla    
u:     RadNud RadNud Clo    RadNud 
v:     RadNud RadNud Clo    RadNud 
temp:  RadNud RadNud Clo    RadNud 
salt:  RadNud RadNud Clo    RadNud 
tke:   Gra    Gra    Clo    Gra
        svn_url: https://www.myroms.org/svn/src/trunk
        svn_rev: 631M
        code_dir: /home/aruba/vol1/serofeev/ROMS_3.6
        header_dir: /home/aruba/vol1/serofeev/ROMS_3.6/ROMS/Include
        header_file: ak_or.h
        os: Linux
        cpu: x86_64
        compiler_system: pgi
        compiler_command: /usr/local/pgi/linux86-64/2012/mpi/mpich/bin/mpif90
        compiler_flags:  -O3 -Mfree
        tiling: 002x008
        history: ROMS/TOMS, Version 3.6, Sunday - December 27, 2015 -  6:35:52 AM
        ana_file: ROMS/Functionals/ana_btflux.h, ROMS/Functionals/ana_hmixcoef.h, ROMS/Functionals/ana_nudgcoef.h, ROMS/Functionals/ana_rain.h, ROMS/Functionals/ana_stflux.h
        CPP_options: AK_OR, ADD_FSOBC, ADD_M2OBC, ANA_BSFLUX, ANA_BTFLUX, ANA_RAIN, ANA_SSFLUX, ASSUMED_SHAPE, AVERAGES, BULK_FLUXES, CURVGRID, DJ_GRADPS, DOUBLE_PRECISION, LONGWAVE, MASKING, MIX_S_TS, MIX_S_UV, MPI, MY25_MIXING, NONLINEAR, NONLIN_EOS, N2S2_HORAVG, POWER_LAW, PROFILE, K_GSCHEME, RADIATION_2D, !RST_SINGLE, SALINITY, SOLAR_SOURCE, SOLVE3D, SPLINES, SPONGE, SSH_TIDES, TS_U3HADVECTION, TS_C4VADVECTION, TS_DIF2, TS_PSOURCE, UV_ADV, UV_COR, UV_U3HADVECTION, UV_C4VADVECTION, UV_QDRAG, UV_PSOURCE, UV_TIDES, UV_VIS2, VAR_RHO_2D

**Comment by barriern** [comment]
As I said, you need to change `Dimension in time`. Replace `time` by `ocean_time`. Same for `scrum_time`, replace it by `ocean_time`.
