### ISSUE TITLE
ichthyop[severe] DataBTree doesnt start with TREE

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#38]
Hello, 
I have a "new" error, never seen before 

ichthyop[severe] DataBTree doesnt start with TREE | java.lang.IllegalStateException: DataBTree doesnt start with TREE
ichthyop[severe] [Simulation] Initialisation failed (performing: SETUP)

I did not do anything different in my configuration, just downloaded ichthyop 3.3.11 on my ubuntu computer, no error with maven or anything before running the preview to chek if eveything was fine.
Thank you in advance for your help,

**Comment by barriern** [comment]
Hi Celine

Could you please send me your configuration files?

Thanks,

Nicolas

**Comment by barriern** [comment]
Hi Celine. 

Could you please try to run the code by providing the configuration file as an additional argument?

This should give something like this:

```
java -jar target/ichthyop-3.3.11-jar-with-dependencies.jar /my/folder/etudeMethodoBarrier3D.xml
```

And send me the text that is returned by your Terminal?

Thanks

Nicolas

**Comment by CelineBarrier** [comment]
here is the terminal output 

ichthyop[info] ===== Simulation started =====
ichthyop[info] ++++ Run 1 / 1
ichthyop[info] Setting up...
ichthyop[severe] An error occured while running the simulation | java.lang.IllegalStateException: DataBTree doesnt start with TREE
  ucar.nc2.iosp.hdf5.DataBTree$Node.<init>(DataBTree.java:175)
  ucar.nc2.iosp.hdf5.DataBTree$Node.first(DataBTree.java:241)
  ucar.nc2.iosp.hdf5.DataBTree$DataChunkIterator.<init>(DataBTree.java:137)
  ucar.nc2.iosp.hdf5.DataBTree.getDataChunkIteratorFilter(DataBTree.java:61)
  ucar.nc2.iosp.hdf5.H5tiledLayoutBB.<init>(H5tiledLayoutBB.java:112)
  ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:162)
  ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:141)
  ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2020)
  ucar.nc2.Variable.reallyRead(Variable.java:874)
  ucar.nc2.Variable._read(Variable.java:845)
  ucar.nc2.Variable._read(Variable.java:891)
  ucar.nc2.Variable.read(Variable.java:709)
  ucar.nc2.Variable.read(Variable.java:655)
  org.previmer.ichthyop.util.NCComparator.compare(NCComparator.java:120)
  org.previmer.ichthyop.util.NCComparator.compare(NCComparator.java:66)
  java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
  java.base/java.util.TimSort.sort(TimSort.java:220)
  java.base/java.util.Arrays.sort(Arrays.java:1515)
  java.base/java.util.ArrayList.sort(ArrayList.java:1750)
  org.previmer.ichthyop.dataset.DatasetUtil.sort(DatasetUtil.java:113)
  org.previmer.ichthyop.dataset.Mars3dDataset.openDataset(Mars3dDataset.java:64)
  org.previmer.ichthyop.dataset.MarsCommon.setUp(MarsCommon.java:145)
  org.previmer.ichthyop.dataset.Mars3dCommon.setUp(Mars3dCommon.java:133)
  org.previmer.ichthyop.dataset.Mars3dDataset.setUp(Mars3dDataset.java:54)
  org.previmer.ichthyop.manager.DatasetManager.setupPerformed(DatasetManager.java:113)
  org.previmer.ichthyop.manager.SimulationManager.fireSetupPerformed(SimulationManager.java:426)
  org.previmer.ichthyop.manager.SimulationManager.setup(SimulationManager.java:381)
  org.previmer.ichthyop.IchthyopBatch.run(IchthyopBatch.java:90)
  java.base/java.lang.Thread.run(Thread.java:829)

**Comment by barriern** [comment]
Hi Celine.

This seems to be an issue with the input file (the HDF5 library does not seem to be able to read it).

The only way for me to look at the issue in more details would be to have the Mars files.

Do you think you can send them to me? Via Dropbox or whatsoever?

Nicolas

**Comment by CelineBarrier** [comment]
Of course, 
I send you a google drive link on your email.
This is it's strange because it's new, I've always used the same hydrodynamic files, and never had this error before

**Comment by barriern** [comment]
Hi Celine,
I was able to run the code with your configuration files, without any problems. Can you try the following?
- Reinstall the NetCDF and HDF5 library. Open a Terminal and type:
``` 
sudo apt install libhdf5-dev libnetcdf-dev
```
- Eventually recompile Ichthyop (in the Ichthyop folder, `mvn package`). 

We can have a quick chat if you still have issues.

**Comment by CelineBarrier** [comment]
Thank you Nicolas, 

I think we need a quick chat yes,

My NetCDF and HDF5 librairies were ok, apparently
sudo apt install libhdf5-dev libnetcdf-dev
[sudo] Mot de passe de barrier_c : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libhdf5-dev est déjà la version la plus récente (1.10.4+repack-11ubuntu1).
libnetcdf-dev est déjà la version la plus récente (1:4.7.3-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 55 non mis à jour.

when I did mvn -B package everything was fine except some warnings below

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

+ I work on ubuntu, I tried the same run with my intern computer on Windows and he got the same error.

**Comment by barriern** [comment]
Problem has been temporarily solved by deactivating the sorting of NetCDF files.
