### ISSUE TITLE
Mercator data

### ISSUE THREAD

**Issue by majambo** [ichthyop/ichthyop#4]
Hi everyone,

[glorys.zip](https://github.com/ichthyop/ichthyop/files/5486674/glorys.zip)
I have been working with Ichthyop for quite sometime and I have a previous setup where I used mercator data and everything is loading perfectly but when I download another file from Copernicus, I get this error
java.lang.NullPointerException: Could not retrieve parameter dataset.mercator2d/gridt_pattern
I can't figure out where the issue is. I have attached the original data, corrected data using python script and xml files.

Thanks
Majambo

**Comment by barriern** [comment]
Hi Majambo

This should be corrected in the most recent version of Ichthyop (3.3.5).

Nicolas

**Comment by majambo** [comment]
Thanks Barriern,
I have installed the recent version but gets this error message
ichthyop[severe] Error occured reading 2020_11_04_Hp_config_mercactor2d.xml 
Error on line 1 of document file:/C:/Users/Hp/Documents/ichthyop-master/target/cfg/2020_11_04_Hp_config_mercactor2d.xml: Invalid encoding name "Cp1252". | java.io.IOException: Error occured reading 2020_11_04_Hp_config_mercactor2d.xml 
Error on line 1 of document file:/C:/Users/Hp/Documents/ichthyop-master/target/cfg/2020_11_04_Hp_config_mercactor2d.xml: Invalid encoding name "Cp1252".

**Comment by barriern** [comment]
Hi Majambo

I have updated the Ichthyop version to 3.3.6, with a patch correction. For some reasons, there are encoding issues with Windows, which I have tried to fix. 

To convert your file from Cp1252 to UTF-8, follow these steps:
- Open the file with Notepad, and replace "Cp1252" by "UTF-8"
- Click on "Save As" and change the Encoding option to "UTF-8".

It should work

Nicolas

**Comment by majambo** [comment]
Hi Barriern,

The update works now with Mercator data.

Thanks
