### ISSUE TITLE
Simulation aborted when launched on a server with a .slurm 

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#40]
Hello, 
I have a new issue. I would like to run my simulations on my university server. I wrote a .slurm to do it. It seems that the simulation initializes correctly and then suddenly stops without giving an error message. Do I have to specify something in the .slurm or in the .xml configuration file to run simulations this way?
Does my system needs a particular java configuration other than the usual one to run Ichthytop? 
Thank you in advance for your reply,
Céline

**Comment by barriern** [comment]
Hi Celine

I am not very familiar with SLURM. In PBS, generally there is a log file. Do you have something similar?

One possible reason is a too short walltime or a too small memory allocated.
