### ISSUE TITLE
Configuration for MEDSEA_MULTIYEAR_PHY model (NEMO database)

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#46]
Dear All,

I use a specific model, and I would like your opinion/help to configure Ichthyop in order to carry out simulations all over the Mediterranean.

Below, a panoply capture of the variables gathered in the files reconstituted from Mercator ocean.

netcdf file:/C:/Users/barrier_c/201409120000.nc {
  dimensions:
    record = UNLIMITED;   // (2 currently)
    lon = 1016;
    time = 15;
    lat = 380;
    depth = 16;
  variables:
    float lon(lon=1016);
      :long_name = "longitude";
      :units = "degrees_east";
      :standard_name = "longitude";
      :axis = "X";
      :_ChunkSizes = 1016; // int
      :_CoordinateAxisType = "Lon";
      :valid_min = -6.0f; // float
      :valid_max = 36.291668f; // float

    double time(time=15);
      :units = "minutes since 1900-01-01 00:00:00";
      :standard_name = "time";
      :long_name = "time";
      :axis = "T";
      :calendar = "standard";
      :_ChunkSizes = 1; // int
      :_CoordinateAxisType = "Time";
      :valid_min = 6.030936E7; // double
      :valid_max = 6.032952E7; // double

    float lat(lat=380);
      :long_name = "latitude";
      :units = "degrees_north";
      :standard_name = "latitude";
      :axis = "Y";
      :_ChunkSizes = 380; // int
      :_CoordinateAxisType = "Lat";
      :valid_min = 30.1875f; // float
      :valid_max = 45.979168f; // float

    float zos(record=2, time=15, lat=380, lon=1016);
      :_FillValue = 1.0E20f; // float
      :units = "m";
      :standard_name = "sea_surface_height_above_geoid";
      :long_name = "sea surface height";
      :coordinates = "time lat lon";
      :missing_value = 1.0E20f; // float
      :_ChunkSizes = 1, 380, 1016; // int

    float depth(depth=16);
      :units = "m";
      :standard_name = "depth";
      :long_name = "depth";
      :axis = "Z";
      :positive = "down";
      :_ChunkSizes = 141; // int
      :_CoordinateAxisType = "Height";
      :_CoordinateZisPositive = "down";
      :valid_min = 1.0182366f; // float
      :valid_max = 51.37986f; // float

    float so(record=2, time=15, depth=16, lat=380, lon=1016);
      :_FillValue = 1.0E20f; // float
      :units = "0.001";
      :standard_name = "sea_water_salinity";
      :long_name = "salinity";
      :coordinates = "time depth lat lon";
      :missing_value = 1.0E20f; // float
      :_ChunkSizes = 1, 36, 95, 254; // int

    float bottomT(record=2, time=15, lat=380, lon=1016);
      :_FillValue = 1.0E20f; // float
      :units = "degrees_C";
      :standard_name = "sea_water_potential_temperature_at_sea_floor";
      :long_name = "sea floor potential temperature";
      :coordinates = "time lat lon";
      :missing_value = 1.0E20f; // float
      :_ChunkSizes = 1, 380, 1016; // int

    float thetao(record=2, time=15, depth=16, lat=380, lon=1016);
      :_FillValue = 1.0E20f; // float
      :units = "degrees_C";
      :standard_name = "sea_water_potential_temperature";
      :long_name = "potential temperature";
      :coordinates = "time depth lat lon";
      :missing_value = 1.0E20f; // float
      :_ChunkSizes = 1, 36, 95, 254; // int

    float uo(record=2, time=15, depth=16, lat=380, lon=1016);
      :_FillValue = 1.0E20f; // float
      :units = "m s-1";
      :standard_name = "eastward_sea_water_velocity";
      :long_name = "eastward ocean current velocity";
      :coordinates = "time depth lat lon";
      :missing_value = 1.0E20f; // float
      :_ChunkSizes = 1, 36, 95, 254; // int

    float vo(record=2, time=15, depth=16, lat=380, lon=1016);
      :_FillValue = 1.0E20f; // float
      :units = "m s-1";
      :standard_name = "northward_sea_water_velocity";
      :long_name = "northward ocean current velocity";
      :coordinates = "time depth lat lon";
      :missing_value = 1.0E20f; // float
      :_ChunkSizes = 1, 36, 95, 254; // int

  // global attributes:
  :title = "Horizontal Velocity (3D) - Daily Mean";
  :FROM_ORIGINAL_FILE__field_type = "daily_mean_centered_at_time_field";
  :source = "MFS E3R1";
  :institution = "Centro Euro-Mediterraneo sui Cambiamenti Climatici - CMCC, Italy";
  :contact = "servicedesk.cmems@mercator-ocean.eu";
  :references = "Please check in CMEMS catalogue the INFO section for product MEDSEA_MULTIYEAR_PHY_006_004 - http://marine.copernicus.eu ";
  :comment = "Please check in CMEMS catalogue the INFO section for product MEDSEA_MULTIYEAR_PHY_006_004 - http://marine.copernicus.eu ";
  :Conventions = "CF-1.0";
  :bulletin_date = "20200901";
  :bulletin_type = "reanalysis";
  :_CoordSysBuilder = "ucar.nc2.dataset.conv.CF1Convention";
  :history = "Mon May  2 13:19:25 2022: ncks -A 201409120000_cur.nc 201409120000_cat.nc\nMon May  2 12:43:39 2022: ncecat 20140901120000_20140915120000_cur.nc 20140916120000_20140930120000_cur.nc 201409120000_cur.nc\nData extracted from dataset http://localhost:8080/thredds/dodsC/med-cmcc-cur-rean-d";
  :NCO = "netCDF Operators version 4.9.3 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)";
  :history_of_appended_files = "Mon May  2 13:19:25 2022: Appended file 201409120000_cur.nc had following \"history\" attribute:\nMon May  2 12:43:39 2022: ncecat 20140901120000_20140915120000_cur.nc 20140916120000_20140930120000_cur.nc 201409120000_cur.nc\nData extracted from dataset http://localhost:8080/thredds/dodsC/med-cmcc-cur-rean-d\nMon May  2 13:19:08 2022: Appended file 201409120000_temp.nc had following \"history\" attribute:\nMon May  2 13:06:24 2022: ncecat 20140901120000_20140915120000_temp.nc 20140916120000_20140930120000_temp.nc 201409120000_temp.nc\nData extracted from dataset http://localhost:8080/thredds/dodsC/med-cmcc-tem-rean-d\nMon May  2 13:18:58 2022: Appended file 201409120000_sal.nc had following \"history\" attribute:\nMon May  2 12:52:37 2022: ncecat 20140901120000_20140915120000_sal.nc 20140916120000_20140930120000_sal.nc 201409120000_sal.nc\nData extracted from dataset http://localhost:8080/thredds/dodsC/med-cmcc-sal-rean-d\n";
}

![image](https://user-images.githubusercontent.com/63110270/166810310-5dc02b1d-3dae-4b3f-8544-08beed6fc9bd.png)

I don't know which configuration to choose in the Ichthyop menus, I take your advice or your feedback on these models with pleasure!
Thank you !

**Comment by barriern** [comment]
Hi Celine.

File provided by CEMS are reinterpolated, meaning that they are not fully compatible with the NEMO settings. Instead, You can use the configuration file [cfg-mercator3d.xml.txt](https://github.com/ichthyop/ichthyop/files/8630123/cfg-mercator3d.xml.txt).

You will need to download the static grid files as well (containing the `mask`, `e1t`, ... variables) and the new Ichthyop release (3.3.12). Indeed, your NetCDF time is in minutes, which was not implemented in Ichthyop.

I leave the issue opened, tell me if you have any troubles. If it works, please close the issue.

**Comment by CelineBarrier** [comment]
Thanks you,
For users wishing to use the MEDSEA_MULTIYEAR_PHY_006_004 model (https://resources.marine.copernicus.eu/product-detail/MEDSEA_MULTIYEAR_PHY_006_004/INFORMATION), here is the method: 
- download the latest version of Ichthyop 3.3.12
- create an account on Copernicus and download the desired data
- download the following additional data (all static files) to make the "cfg-mercator3d.xml.txt" configuration file sent above work, by connecting with your mercator account with an FTP client on : my server .cmems-du.eu and /Core/MEDSEA_MULTIYEAR_PHY_006_004/MEDSEA_MULTIYEAR_PHY_006_004-statics

So far it works for me, but I always get an error when launching the preview to check that the files are read by Ichthyop:

![image](https://user-images.githubusercontent.com/63110270/167595791-d48c2603-769a-4dd8-8968-4a530de86cf4.png)
