### ISSUE TITLE
Mercator 3d release/recruitment zones definition

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#48]
Dear all, 
I have a new question about mercator 3d parametrisation.
I usually draw my polygons with QGIS, entering a layered hydrodynamic file to be sure the polygons are not in the "earth mask" (screenshot).
![image](https://user-images.githubusercontent.com/63110270/168663136-dcacf61c-5b1e-4344-8293-259907bcdd64.png)
I drew my polygons correctly (I think), however, when running the simulation, I have the following error (screenshot)
![image](https://user-images.githubusercontent.com/63110270/168662929-5acf5c4a-4594-4df3-8720-a17e2c597427.png)
I launch 2 million particles. My simulation runs giving this error only on certain polygons. I do not understand why.
I attached my configuration file as well as my source and sink polygon files.

[polyGrandeEmpriseCrabeBleuSourceFinalCor.txt](https://github.com/ichthyop/ichthyop/files/8702704/polyGrandeEmpriseCrabeBleuSourceFinalCor.txt)
[mercator3DBlueCrabFall2014DVM2millionp.txt](https://github.com/ichthyop/ichthyop/files/8702705/mercator3DBlueCrabFall2014DVM2millionp.txt)
[polyGrandeEmpriseCrabeBleuPuitFinalCor.txt](https://github.com/ichthyop/ichthyop/files/8702706/polyGrandeEmpriseCrabeBleuPuitFinalCor.txt)

Thank you very much for your reply !

**Comment by barriern** [comment]
Hi Celine.
I think that the answer lies in the error message. Given the above picture, the zone seems very small compared to the size of one ocean cell. In this case, Ichthyop will fail releasing the particle. In the Ichthyop preview, you will see the zone definitions. You can check whether the zones are indeed well defined or not.
Nicolas

**Comment by CelineBarrier** [comment]
Thank you Nicolas, 
Indeed, I systematically use the "preview" option to check my zones. Here, it worked, it was then when launching the simulation that there was an error. I "fixed" this by drawing coarser polygons (mercator3d's resolution being 4/5km), it's not satisfactory, but I'll refine it later after my preliminary tests.
Thanks for your answer,
