### ISSUE TITLE
Older ichthyop .xml files not working with 3.3.6

### ISSUE THREAD

**Issue by jesskolbusz** [ichthyop/ichthyop#5]
Have upgraded through Maven and github and re-complied 3.3.6.. but when I go into ichthyop 3.3.6 and try to load .xml files 
"org.jdom2.input.JDOMParseException: Error on line 1 of document file
Invalid encoding name "Cp1252""

Any help would be great!

**Comment by barriern** [comment]
This issue was in fact in version 3.3.5, in which configuration files were saved in Cp1252 encoding with Windows. What you can do is:
- Edit the configuration file using `Notepad` and replace `Cp1252` by `UTF-8`
- Click on `Save As` and save your file **with the UTF-8 encoding**

**Comment by jesskolbusz** [comment]
Thank you, yes this has worked! I went straight from 3.3.3 to 3.3.6 - seems to be good now though with this fix. 
Thanks!
