### ISSUE TITLE
Error reading dataset grid dimensions XI

### ISSUE THREAD

**Issue by cuchisavila** [ichthyop/ichthyop#50]
Hi
I am getting his error. 

_Error reading dataset grid dimensions XI. java.lang.NullPointerException: Cannot invoke "ucar.nc2.Dimension.getLength()" because the return value of "ucar.nc2.NetcdfFile.findDimension(String)" is null | java.io.IOException: Error reading dataset grid dimensions XI. java.lang.NullPointerException: Cannot invoke "ucar.nc2.Dimension.getLength()" because the return value of "ucar.nc2.NetcdfFile.findDimension(String)" is null_

I have opened the grid .nc file and treid figuring out what it is what it wants and I have not been able to fix it

![Screen Shot 2022-05-19 at 3 01 52 PM](https://user-images.githubusercontent.com/39143475/169412053-04680bcd-d874-4421-9874-6d1c52e7539b.png)_

earlier i was getting this error from tyirng to teach the parameters:
_Problem reading dataset longitude. ucar.ma2.InvalidRangeException: Illegal Range for dimension 0: last requested 2031 > max 2030 | java.io.IOException: Problem reading dataset longitude. ucar.ma2.InvalidRangeException: Illegal Range for dimension 0: last requested 2031 > max 2030_

the attached is a screen shot of the grid file parameters and a view of the ROMS parameters in ichthyop (above) and the other is a screen shot of the ROMS file and Time parameters ( bellow)
![Screen Shot 2022-05-19 at 3 05 35 PM](https://user-images.githubusercontent.com/39143475/169412364-11111c6d-460c-4850-8628-d0fcc5cf697e.png)

**Comment by barriern** [comment]
Hi.

In order to have a closer look at it, it would be good if you provide me with the NetCDF files (grid + uv, only a few time steps is enough), and your configuration file.

A quick glance tells me that instead of reading the XI dimension from the grid file, it reads it from the UV file, in which the dimension does not exist.

**Comment by cuchisavila** [comment]
Hi
There are thousands of ROMS files. How would I share that with you? Is just sending you one enough? It would be too big to send if I had to send you all of them. 
also which one is the configuration file?

**Comment by barriern** [comment]
The configuration file is the `.xml` file. And for the NetCDF files, send me 2 or three files, it should be enough. If possible include the grid file.

**Comment by cuchisavila** [comment]
Im trying to attach the .zip file but its not letting me upload it( i get its not included in the list mssage

**Comment by cuchisavila** [comment]
Apparently a folder with all the files was too big
so here it is in smaller bites
ROMs
[uv_avg_Exp42_0003.nc.zip](https://github.com/ichthyop/ichthyop/files/8739854/uv_avg_Exp42_0003.nc.zip)
[uv_avg_Exp42_0002.nc.zip](https://github.com/ichthyop/ichthyop/files/8739855/uv_avg_Exp42_0002.nc.zip)
[uv_avg_Exp42_0001.nc.zip](https://github.com/ichthyop/ichthyop/files/8739856/uv_avg_Exp42_0001.nc.zip)

**Comment by cuchisavila** [comment]
[2022_05_19_ROMs_config_roms2d4.xml.zip](https://github.com/ichthyop/ichthyop/files/8739867/2022_05_19_ROMs_config_roms2d4.xml.zip)
Configuration file

the gird file it too big and will not allow me to upload it

**Comment by cuchisavila** [comment]
This is the information from the grid file as opened in R
> nc_open("grd_wcofs_large_visc200.nc")
File grd_wcofs_large_visc200.nc (NC_FORMAT_CLASSIC):

     31 variables (excluding dimension variables):
        double xl[]   
            long_name: domain length in the XI direction
            units: meter
        double el[]   
            long_name: domain length in the ETA direction
            units: meter
        char spherical[]   
            long_name: Grid type logical switch
        double h[xi_rho,eta_rho]   
            long_name: Final bathymetry at RHO-points
            units: meter
            field: bath, scalar
        double f[xi_rho,eta_rho]   
            long_name: Coriolis parameter at RHO-points
            units: second-1
            field: Coriolis, scalar
        double pm[xi_rho,eta_rho]   
            long_name: curvilinear coordinate metric in XI
            units: meter-1
            field: pm, scalar
        double pn[xi_rho,eta_rho]   
            long_name: curvilinear coordinate metric in ETA
            units: meter-1
            field: pn, scalar
        double dndx[xi_rho,eta_rho]   
            long_name: xi derivative of inverse metric factor pn
            units: meter
            field: dndx, scalar
        double dmde[xi_rho,eta_rho]   
            long_name: eta derivative of inverse metric factor pm
            units: meter
            field: dmde, scalar
        double x_rho[xi_rho,eta_rho]   
            long_name: x location of RHO-points
            units: meter
        double y_rho[xi_rho,eta_rho]   
            long_name: y location of RHO-points
            units: meter
        double x_psi[xi_psi,eta_psi]   
            long_name: x location of PSI-points
            units: meter
        double y_psi[xi_psi,eta_psi]   
            long_name: y location of PSI-points
            units: meter
        double x_u[xi_u,eta_u]   
            long_name: x location of U-points
            units: meter
        double y_u[xi_u,eta_u]   
            long_name: y location of U-points
            units: meter
        double x_v[xi_v,eta_v]   
            long_name: x location of V-points
            units: meter
        double y_v[xi_v,eta_v]   
            long_name: y location of V-points
            units: meter
        double lon_rho[xi_rho,eta_rho]   
            long_name: longitude of RHO-points
            units: degree_east
        double lat_rho[xi_rho,eta_rho]   
            long_name: latitude of RHO-points
            units: degree_north
        double lon_psi[xi_psi,eta_psi]   
            long_name: longitude of PSI-points
            units: degree_east
        double lat_psi[xi_psi,eta_psi]   
            long_name: latitude of PSI-points
            units: degree_north
        double lon_u[xi_u,eta_u]   
            long_name: longitude of U-points
            units: degree_east
        double lat_u[xi_u,eta_u]   
            long_name: latitude of U-points
            units: degree_north
        double lon_v[xi_v,eta_v]   
            long_name: longitude of V-points
            units: degree_east
        double lat_v[xi_v,eta_v]   
            long_name: latitude of V-points
            units: degree_north
        double mask_rho[xi_rho,eta_rho]   
            long_name: mask on RHO-points
            option_0: land
            option_1: water
        double mask_u[xi_u,eta_u]   
            long_name: mask on U-points
            option_0: land
            option_1: water
        double mask_v[xi_v,eta_v]   
            long_name: mask on V-points
            option_0: land
            option_1: water
        double mask_psi[xi_psi,eta_psi]   
            long_name: mask on PSI-points
            option_0: land
            option_1: water
        double angle[xi_rho,eta_rho]   
            long_name: angle between xi axis and east
            units: radians
        double visc_factor[xi_rho,eta_rho]   
            long_name: horizontal viscosity sponge factor
            valid_min: 0
            coordinates: lon_rho lat_rho

     8 dimensions:
        xi_rho  Size:696 (no dimvar)
        eta_rho  Size:2032 (no dimvar)
        xi_u  Size:695 (no dimvar)
        eta_u  Size:2032 (no dimvar)
        xi_v  Size:696 (no dimvar)
        eta_v  Size:2031 (no dimvar)
        xi_psi  Size:695 (no dimvar)
        eta_psi  Size:2031 (no dimvar)

    2 global attributes:
        type: ROMS GRID file
        title: West Coast Ocean Forecast System (WCOFS)
>

**Comment by barriern** [comment]
Without the grid file, I cannot really help... Can you send it through a cloud, like Dropbox or Google Drive?

**Comment by barriern** [comment]
Ok I see the problem. Can you try with the given jar file?

https://filesender.renater.fr/?s=download&token=9bfd782c-04c7-4fc4-b7fb-e05b77924323

The problem seems to be that Ichthyop tries to read dimensions from the `UV` file and not from the grid file. I have corrected that im the current jar. If it works, I will commit the change.

Nicolas

**Comment by barriern** [comment]
The error message indicates that the `.jar` file does not exist. It has nothing to do with the grid. Are you sure you ran the command on the proper folder?

**Comment by cuchisavila** [comment]
I ran it the same way I run the example that is included in the instructions, and that worked
