### ISSUE TITLE
How to use getm model on ichthyop

### ISSUE THREAD

**Issue by RuoLinCunJi** [ichthyop/ichthyop#52]
as the title describes
How do I apply a model other than the preset model？
I sincerely hope you can answer and solve my problem！

**Comment by barriern** [comment]
Hi. Sorry I completely missed your issue. The idea would be to add a new Dataset class that includes all the requirements of the getm model.

However, we decided to put energy mainly in the management of the most common grids (Roms, Nemo, Mars).

Nicolas

**Comment by RuoLinCunJi** [comment]
Thanks for your reply, now I have another problem.
I can make sure that the point is indeed in the ocean (in my nc file) and not out of range.
How can I solve this problem, looking forward to your reply!
cheers!

`ichthyop[info] Reading NetCDF variables...
ichthyop[severe] {Release stain} Center of the stain [lat: 34.5; lon: 120.0] is not in water or out of the domain. Fixed that in section Release stain. | java.io.IOException: {Release stain} Center of the stain [lat: 34.5; lon: 120.0] is not in water or out of the domain. Fixed that in section Release stain.
ichthyop[severe] [Simulation] Initialisation failed`

**Comment by RuoLinCunJi** [comment]
[2022_07_11_admin_config_roms2d.txt](https://github.com/ichthyop/ichthyop/files/9091448/2022_07_11_admin_config_roms2d.txt)
[lat&lon&mask.xlsx](https://github.com/ichthyop/ichthyop/files/9091451/lat.lon.mask.xlsx)
There may be some format problems, please forgive me.Thank you.
Cheers

**Comment by barriern** [comment]
I need the NetCDF files, not the XLS

**Comment by RuoLinCunJi** [comment]
Hello Nicolas!
 I really need your help, I hope you can reply me as soon as possible，thank you again sincerely！
Cheers

**Comment by barriern** [comment]
Hi.

In the mask_rho.nc file that you sent, all data are missing. I will need the right file to investigate the issue. Can you send it via Google Drive or something alike? 

Nicolas

**Comment by RuoLinCunJi** [comment]
[mask_rho (2).zip](https://github.com/ichthyop/ichthyop/files/9130642/mask_rho.2.zip)
I m so sorry for that.

**Comment by RuoLinCunJi** [comment]
My original file is 10GB in size and I really don't know how to send it to you.

**Comment by barriern** [comment]
Hi again.

I built some dummy file to test. I think the issue comes from the fact that in your file, the longitudes and latitudes contain missing values. This is something that is generally found in parallel ocean model outputs: for optimization purposes, the land-only processors are discarded (cf. figure).

Because of these missing values, Ichthyop fails to start properly. Do you have access to a grid file, where longitudes and latitudes are not masked?

Nicolas

![figure_mask](https://user-images.githubusercontent.com/32549583/179487984-d59f9210-2fd5-46f2-a15b-63ce56119298.png)

**Comment by RuoLinCunJi** [comment]
Hi Nicolas!
This is because the original terrain file automatically becomes NaN after getm runs, so as long as I change the NaN to the correct value, it will be fine?
Cheers!
R.Lin

**Comment by RuoLinCunJi** [comment]
[https://drive.google.com/file/d/1V76HQSKiXV_rUonFLcpWiHl-cUUdkHbw/view?usp=sharing](url)
Hi Nicolas!
This is the a simple nc file I ran on ichthyop, now I have another problem, I don't know why, my particles don't move with time.
ubar&vbar: I changed the original NaN value to 0. (p.s: Maybe it was changed incorrectly?)
Cheers
R.Lin

**Comment by RuoLinCunJi** [comment]
Hi Nicolas
I've tried many ways to change it to work correctly, but I've failed. I really hope you can give me some valuable advice, thank you very much!
![image](https://user-images.githubusercontent.com/108501826/180359133-404b488d-b137-4bfb-b4cd-b38e27f1cedf.png)
it just can't move.

**Comment by barriern** [comment]
Hi. I have looked at your `test_5.nc` file, and it seems normal that your particles don't move. `ubar` and `vbar` are 0 everywhere.

**Comment by RuoLinCunJi** [comment]
So how should I modify my pm pn? Is it to make them equal to 1/X &1/Y?

**Comment by barriern** [comment]
On your `getm` grid, what grid informations do you have? You need to set `pm` and `pn` so that it is equal to the cell length and width

**Comment by RuoLinCunJi** [comment]
My grid file shows me the dx&dy both all equal to 1000m,so i modify pm&pn equal to 0.001,but it still don't move.

**Comment by barriern** [comment]
It worked with the following configuration file.
[2022_07_11_admin_config_roms2d.xml.txt](https://github.com/ichthyop/ichthyop/files/9168521/2022_07_11_admin_config_roms2d.xml.txt)

**Comment by RuoLinCunJi** [comment]
Dear Nicolas
Thank you very much for your help, now the program can run normally. 
Once again I express my sincere thanks to you.
R.Lin

**Comment by barriern** [comment]
You're welcome. I close the issue in this case.
