### ISSUE TITLE
Error : unknown compression method

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#53]
Hello,
I have a new error, which only happens with my recent hydrodynamic files (I use MARS3D, and the error only appears from 2019, until 2021). These are simulations made with Ichthyop 3.3.11. 
The complete error is in the attached .txt file.
Thanks for your help !
[slurm-18529.txt](https://github.com/ichthyop/ichthyop/files/9490700/slurm-18529.txt)

**Comment by barriern** [comment]
Hi Celine.

It seems to be an issue with the NetCDF itself, not Ichthyop. I therefore cannot debug it as it is. Could you please send me the `champs_meno_BE202011.nc` file and the configuration files that you use? I will try to reproduce the issue and see if some manipulations on the file can help.

Thanks

Nicolas

**Comment by CelineBarrier** [comment]
Hello, 
Thank you for your reply.
[urchinsFall2020.txt](https://github.com/ichthyop/ichthyop/files/9494908/urchinsFall2020.txt)

Here is my configuration file and a a link for the .nc file : https://drive.google.com/file/d/18karBZs2ta_2LqqRm5UfrRG_4xTE8Hlu/view?usp=sharing

I specify that I have this error for "recent" files, from 2019 (so maybe it's due to a different way of making netcdf files?)

**Comment by CelineBarrier** [comment]
Thanks,
Do you think this is the source of the error?
I am directly in contact with the person who compiles the data to make my netcdf files, I will report this error and this NCO output to him to see what he thinks about it and what he can do.
