### ISSUE TITLE
Rule to avoid errors in the design of release zones?

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#54]
Hello,
I have a general question: Is there with ichthyop a "rule" of good practice to avoid errors like "Release zone 1 has not been attributed any particle. It may be too small compared to other release zones or its definition may be flawed".

For example, in one of my simulations with coastal behavior = bouncing, I got the error above with the design schematized below.

![schemaIchthyop](https://user-images.githubusercontent.com/63110270/193815101-ad967d5c-ea9d-4c82-adc3-849269d06ae0.jpg)

What is the best practice to generalize and avoid this kind of error? 
Do you think it is necessary as a precaution to leave each time 1 grid cell of the hydrodynamic model used free before drawing the polygon? More than 1 ?

Thank you for your feedback, I think it can be useful to all users.

**Comment by barriern** [comment]
Hi Celine. 
No general guidelines regarding this. The idea is generally to make sufficiently large polygons to make sure that particles can be released. Could you send the above picture with only the `zone 1` polygon?

**Comment by CelineBarrier** [comment]
yes, the one with the arrow "one of my polygons" is the polygon 1 for example

sometimes I have polygons close to the earth mask (<1 model grid cell) which give no error, and sometimes I have larger polygons with errors, that's why I was asking if there was a tip
