### ISSUE TITLE
Backward Lyapunov exponents (FSLE) to advect particles 

### ISSUE THREAD

**Issue by TRasehlomi** [ichthyop/ichthyop#55]
I am trying to advect particles using the backward FSLE Lyapunov exponents. Is there a specific configuration file I can use for this exercise?

**Comment by barriern** [comment]
Hi @TKzee2027.

I am not really familiar with Lyapunov exponents. But in the case they are provided as regular 2D fields, you can indeed adapt the GlobCurrent configuration.

**Comment by TKzee2027** [comment]
Thank you so much.
