### ISSUE TITLE
Lat Lon Depth points are not water but land 

### ISSUE THREAD

**Issue by lgarcia64** [ichthyop/ichthyop#56]
Hi Nicolas, 

I am having issues releasing particles from a file. I'm having an error saying that too many points are not water but land. However, if I check the croco grid, these points are definitely water. What should I do?

Best,
-Luisa

**Comment by barriern** [comment]
Hi @lgarcia64 

Like this I can't tell. I will need some of your Croco files (a few time-steps is enough), your Ichthyop XML file and your release coordinates.

**Comment by lgarcia64** [comment]
Hi Nicolas, 

Im going to share with you a folder with all files through Google Drive. 
Thanks,
