### ISSUE TITLE
bathymetry that is used in ichthyop

### ISSUE THREAD

**Issue by gliu87** [ichthyop/ichthyop#6]
I'm using ROMS-CROCO for particles tracking, however, I don't know how to define my own "h" variable for the initial locations. It seems that your model uses your own bathymetry, which has some conflicts with my grdfile. I put particles 30m above my seafloor, but after submitting my jobs, some particles are not in 'water' in ichthyop. Is it possible to use my grdfile and release particles?

Thank you~

**Comment by barriern** [comment]
Hi 

Ichthyop reads the `h` variable of the ROMS input file. It does not use its own bathymetry.

Nicolas
