### ISSUE TITLE
Vertical migration + Ichthyop 3.3.12 Mercator setup

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#63]
Dear all,

Would it be possible to configure a vertical migration (time of the day function/ontogenetic function), with a MEDSEA hydrodynamic file (https://data.marine.copernicus.eu/product/MEDSEA_MULTIYEAR_PHY_006_004/description), in Ichthyop 3.3.12. This feature seems to be missing at the moment.

Here is an example of the hydrodynamic model : https://drive.google.com/file/d/1srj8sKlPHv-_-tyh8jbMU2ipHe-hSc-0/view?usp=share_link

Thanks for your feedback,

Cordially

**Comment by barriern** [comment]
Hi @CelineBarrier 

The  inclusion of migration can be added by including some extra parameters in the configuration file, as below.

[cfg-mercator3d.xml.txt](https://github.com/ichthyop/ichthyop/files/11135998/cfg-mercator3d.xml.txt)

These parameters were not included in the original Mercator template because it was first built for 2D simulations.

@barriern

**Comment by CelineBarrier** [comment]
Thank you, 
It works, but there is a problem with my input (the same as give in the drive link in my first message below, all my MERCATOR inputs are like that), so I have the following error after running a preview :

**Comment by barriern** [comment]
Hi @CelineBarrier 

This is because the grid files (`MED-MFC_006_004_coordinates.nc`) contain 141 vertical levels:

```
netcdf MED-MFC_006_004_coordinates {
dimensions:
	latitude = 380 ;
	longitude = 1016 ;
	depth = 141 ;
```

but your input file contain only 16 levels:

```
netcdf MEDSEA2014 {
dimensions:
	depth = 16 ;
	time = 12 ;
	lat = 380 ;
	lon = 1016 ;
```

So either you extract the first 16 levels from the grid file, or you download the dataset over the 141 levels.

@barriern

**Comment by CelineBarrier** [comment]
Yes indeed thank you very much
For users who also need to modify their mask/grid files, it is possible to use NCO (ncks function) (by adapting the names of the files and the desired levels), in my case:

ncks -d depth,0,15 MED-MFC_006_004_coordinates.nc cor-MED-MFC_006_004_coordinates.nc
