### ISSUE TITLE
Release : Total proportion different from 100

### ISSUE THREAD

**Issue by thomasbeneteau** [ichthyop/ichthyop#75]
Hello,

With Ichthyop version 3.3.16, I want to simulate dispersion by setting a proportion of the total number of particles at each release site. However, the sum of the proportions never reaches 1, and an error is returned as a proportion of 99.99999999999996 or 100.00000000000004. 
So I tried setting only one site to a proportion of 0.034 and all the others to 0. The error returned was: "Total proportion must be less equan than 100. Actual proportion is 3.4000000000000004". The same operation with a proportion of 0.0345 gives me: "Total proportion must be less equan than 100. Actual proportion is 3.45". Is there a problem in assigning proportions to decimals? Please note that I assign the proportions manually in the .xml files.

Thanks!

**Comment by barriern** [comment]
Hi Thomas.

Could you please send me your zone file and your total number of particles released? Thanks

**Comment by barriern** [comment]
In the time-mean, here is a small patch where I forced the comparison with a precision factor. I am attending a 3 days workshop so I won't be available a lot during this week. 

https://filesender.renater.fr/?s=download&token=f9359bbb-a9e5-4340-815d-ec4761b1b1f2

**Comment by thomasbeneteau** [comment]
Hello, 
thank you for your quick feedback. I've downloaded the attached patch and the simulation seems to be running, thank you very much. Here is the file for my release zone for a total number of particles of 300,000.

[release_zone.txt](https://github.com/ichthyop/ichthyop/files/11879022/release_zone.txt)
