### ISSUE TITLE
Is Ichthyop parallelized ?

### ISSUE THREAD

**Issue by xzhou473** [ichthyop/ichthyop#76]
Hello,

I was wondering is Ichthyop running parallell or serial ? If it is running parallel, how can I specify the CPUs to run it ? 

Sorry, I didn't find this information in the documents.

**Comment by barriern** [comment]
Hi @xzhou473 

So far Ichthyop runs in sequential. However, there is a tool that allows to run multiple simulations in parallel, using a C++ interface.

https://github.com/ichthyop/ichthyop-mpi

Nicolas
