### ISSUE TITLE
First time project 

### ISSUE THREAD

**Issue by ytmben** [ichthyop/ichthyop#78]
Hello to all,

I am quite new to the ichthyop software and also to working with netCDF type files. I am trying to create a model for larvae expansion in the Mediterranean, but have not yet succeeded in configuring my dataset in order to run the model. I am trying to run a NEMO 3D model Would anyone have a spare moment to check my data and my configuration .xml to guide me? 

Thank you in advance for any help
@ytmben

**Comment by barriern** [comment]
Hi @ytmben 

Welcome to Ichthyop. Sorry for the delay (do not hesitate to send reminders).

Please feel free to send me, via WeTransfer or anything alike, a sample of your input files (Nemo NetCDF files) and of your Ichthyop configuration files.

@barriern

**Comment by ytmben** [comment]
Hi @barriern 
Sorry for taking so long to reply, I actually managed to fix my issue through an old issue that was resolved on this forum that had a .xml configuration ready made for data downloaded from CMEMS. So all is well!
