### ISSUE TITLE
Can ichthyop support curvilinear orthogonal grid?

### ISSUE THREAD

**Issue by Cyuan-hub** [ichthyop/ichthyop#79]
Hi, @barriern, 
I am also quite new to the ichthyop software. I want to create a model to simulate plastic dispersion in the coastal area. However, my hydrodynamic data comes from curvilinear orthogonal grid. Does ichthyop support curvilinear orthogonal grid?
The grid diagram is as follows:
![Grid of study area](https://github.com/ichthyop/ichthyop/assets/104747402/2f838e37-19ec-4811-bc60-1311268df0a6)

**Comment by barriern** [comment]
Hi @Cyuan-hub 

Ichthyop manages curvilinear orthogonal grid, at least the NEMO, ROMS and MARS grid. It uses grid coordinates to compute advection, not geographical ones.
