### ISSUE TITLE
Support for HYCOM (HYBRID COORDINATE OCEAN MODEL)

### ISSUE THREAD

**Issue by oceandiscovery** [ichthyop/ichthyop#8]
This is not an issue in itself, but would it be possible to add HYCOM ([https://www.hycom.org](https://www.hycom.org)) as one of the supported circulation models?

Thank you.

**Comment by barriern** [comment]
Hi.

Yes, it would indeed be a good idea. In the mean time, it is possible to run Ichthyop with Hycom by pre-processing the files to fit the standards of ROMS. 

Nicolas
