### ISSUE TITLE
Using an Ichthyop output file as a release in a new simulation

### ISSUE THREAD

**Issue by ytmben** [ichthyop/ichthyop#80]
Hello again! 

I'm trying to use the Restart mode instead of a release stain in order to experiment with the simulation I want to run, and in the option I am using the netCDF file that I got as the output from a previous simulation. My problem is that for some reason that doesn't work. Even though when I preview the simulation everything is fine, when I try to run it, this is the error that i'm getting. Any one has any idea what could it be?

Cannot invoke "org.previmer.ichthyop.particle.IParticle.init()" because "particle" is null | java.lang.
NullPointerException: Cannot invoke "org.previmer.ichthyop.particle.IParticle.init()" because "particle" is null

**Comment by barriern** [comment]
Hi @ytmben 

Could you please send me the associated files (output file for the restart, ocean currents and Ichthyop XML files) so that I can try to see what is going on? Thanks

**Comment by ytmben** [comment]
Hi @barriern,
I sent you an email with the XML and output files, but my ocean current files are too large for email I think, could you send me your email and I could send them to you by WeTransfer?

Thanks,
Yotam

**Comment by barriern** [comment]
Hi.

You can send the link to nicolas.barrier@ird.fr

**Comment by ytmben** [comment]
Hi @barriern ,
Did you receive my files?

**Comment by barriern** [comment]
Hi @ytmben 

I don't think I received anything. Could you try again? Thanks

**Comment by ytmben** [comment]
Hi @barriern ,
i will send it again today, but since i don't have a premium wetransfer account, the link only lasts 3 days i think

**Comment by barriern** [comment]
Hi @ytmben 
I still dit not receive any file.
Nicolas

**Comment by ytmben** [comment]
Hi @barriern 

sorry for the inconvenience, for some reason the transfer didn't go through. I just finished sending it again, I sent the files in 2 transfers because I forgot to include my output file in the first one. So you should receive my .xml configuration file, my circulation, bathymetry and coordinates cropped files, and my output file. 

Thank you,
Yotam

**Comment by barriern** [comment]
I received the files, I will have a look at the problem.

Nicolas

**Comment by ytmben** [comment]
Hi @barriern 
I never replied back, but the issue was fixed! 
Thank you very much for your help,
I will close this issue since with the new .jar its no longer a problem
