### ISSUE TITLE
simulation using Copernicus data

### ISSUE THREAD

**Issue by mainarabgouveia** [ichthyop/ichthyop#81]
Hi, first, I apologize if these questions do not fit here.

I would like to do simulations on Ichthyop using data from GLORYS12V1 from CMEMS (https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description), in 3D. But I don't know which option I should use.

I have already performed the downloads according to "Configuration for MEDSEA_MULTIYEAR_PHY model (NEMO database) #46", but I only find the MERCATOR2D option in the DATASET.

I got around this by editing the file "cfg-mercator3d.xml.txt" available in "configuring mercatorglorys dataset on ichthyop #62", instead of creating a new xml.

And I'm getting this error:

ichthyop[severe] Error reading U velocity variable. ucar.ma2.InvalidRangeException: Illegal Range for dimension 3: last requested 300 > max 240 | java.io.IOException: Error reading U velocity variable. ucar.ma2.InvalidRangeException: Illegal Range for dimension 3: last requested 300 > max 240
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)

Would this be possible because I cut the Glorys data using the nco tool?

Could you help me, please?

----------------------------------------------- 

ichthyop[info] ===== Simulation started =====
ichthyop[info] [Simulation] Run 1 / 1
ichthyop[info] [Simulation] Initialising...
ichthyop[warning] Ichthyop will recalculate W variable from U and V
ichthyop[warning] Ichthyop assumes that by default the NEMO NetCDF files must be opened in enhanced mode (with scale, offset and missing attributes).
ichthyop[info] read lon, lat & mask from /home/dama-de-ferro/Documents/ich/input/coordenates_testeMaiBG.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated action "Advanced/Transport/Horizontal dispersion"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[info] Opening NEMO dataset
ichthyop[info] {Dataset} Open /home/dama-de-ferro/Documents/ich/input/glorys_20180401.nc
ichthyop[info] Reading NetCDF variables...
ichthyop[severe] Error reading U velocity variable. ucar.ma2.InvalidRangeException: Illegal Range for dimension 3: last requested 300 > max 240 | java.io.IOException: Error reading U velocity variable. ucar.ma2.InvalidRangeException: Illegal Range for dimension 3: last requested 300 > max 240
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)

**Comment by barriern** [comment]
Hi @mainarabgouveia 

Sorry I missed your message. You closed the issue because you were able to fix the problem?

Nicolas

**Comment by mainarabgouveia** [comment]
Hi Nicolas,

Tks for your attention and time.
Yes, I found an example of Mercator 3D and opened it, then changed it to my
settings.
I also solved the other problems by looking at the other issues.
Have a nice day.
Mainara
----------------------------------------------------------------------------------
 *Mainara Biazati Gouveia, PhD Remote Sensing.*

*ORCID: https://orcid.org/0000-0002-6785-1841
<https://orcid.org/0000-0002-6785-1841>*

*ResearchGate: www.researchgate.net/profile/Mainara_Gouveia
<http://www.researchgate.net/profile/Mainara_Gouveia>*
-----------------------------------------------------------------------------------




Em sex., 10 de nov. de 2023 às 10:12, Nicolas Barrier <
***@***.***> escreveu:
