### ISSUE TITLE
[Error] ichthyop[severe] Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by silvaglx** [ichthyop/ichthyop#92]
Hello,

I'm a beginner to ICHYTHYOP tool facing some problems to perform the simulations.  I apologize if this is rather a simple question. 

I've been trying to run ichthyop using my personal COAWST/ROMS 3D dataset as input. I carefully edited and revised the available benguela.nc template to match with my dataset variables. However, I keep receiving "ichthyop[severe] Index 0 out of bounds for length 0" error when initializing the model.  I already performed test simulations with the benguela.nc template and it works just fine.

Here's the whole console output:
```
ichthyop[info] [Simulation] Initialising...
ichthyop[info] {Dataset} Open C:\Users\xavie\ichthyop\input\yaeyama_test_6hrs.nc
ichthyop[info] Release manager setup [OK]
ichthyop[info] Time manager setup [OK]
ichthyop[info] Instantiated action "Advanced/Transport/Advection"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionAgeMonitoring"
ichthyop[info] Instantiated system action "org.previmer.ichthyop.action.SysActionMove"
ichthyop[info] Action manager setup [OK]
ichthyop[info] Output manager setup [OK]
ichthyop[severe] Index 0 out of bounds for length 0 | java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
ichthyop[severe] [Simulation] Initialisation failed (performing: INIT)
```
Here's my project configuration .xml and a 6-hour sample from the dataset I've been trying to use as input:
[.XML and Sample Dataset (~188MB)](https://drive.google.com/file/d/1k95LayGisEBaMbCCyXwKRjSIWLT6jC13/view?usp=sharing)

**Comment by silvaglx** [comment]
Apparently I found the problem. I thought the required input parameter **Averaged time since initialization** was equivalent to my dataset initial date counter (i.e. **dstart** = '2000-01-01T00:00:00'). However, after checking the available roms-benguela.nc dataset I noticed that the equivalent variable used as input for the time since initialization parameter (**scrum_time**) was actually an array of datetime dates equivalent to the **time** variable.

In order for my simulation to run, I therefore selected the same time variable in my dataset (**ocean_time**) as input for both **Dimension in time** and **Averaged time since initialization** tool parameters.  

Although the simulation is working fine now, I got a little bit confused with this two input parameters I would appreciate if anyone could provide an explanation on the main differences and what exactly we should use as input for **Dimension in time** and **Averaged time since initialization**. 

Thank you and sorry for the newbie question!

**Comment by barriern** [comment]
Hi @silvaglx 

Good to know that you solved your issue.

The `Dimension in time` is the name of the time **dimension** on your NetCDF files. The `Averaged time since initialization` is the name of the time **variable**. Sometimes, the time dimension and variable are (and in fact should be) the same and time is therefore considered as a NetCDF coordinate.

For instance, if on Linux you type: 

```ncdump -h roms-benguela.nc
```

You will have the following:

```
netcdf roms-benguela {
dimensions:
	eta_rho = 37 ;
	xi_rho = 25 ;
	time = UNLIMITED ; // (10 currently)
	s_rho = 32 ;
	xi_u = 24 ;
	eta_v = 36 ;
variables:
	float h(eta_rho, xi_rho) ;
	float lat_rho(eta_rho, xi_rho) ;
	float lon_rho(eta_rho, xi_rho) ;
	float mask_rho(eta_rho, xi_rho) ;
	float pm(eta_rho, xi_rho) ;
	float pn(eta_rho, xi_rho) ;
	float salt(time, s_rho, eta_rho, xi_rho) ;
	float scrum_time(time) ;
		scrum_time:units = "seconds since 1900-01-01 00:00:00" ;
	float temp(time, s_rho, eta_rho, xi_rho) ;
	float u(time, s_rho, eta_rho, xi_u) ;
	float ubar(time, eta_rho, xi_u) ;
	float v(time, s_rho, eta_v, xi_rho) ;
	float vbar(time, eta_v, xi_rho) ;
	float zeta(time, eta_rho, xi_rho) ;
```

Dimension names are provided on top. So time dimension here is called `time`.

Variable names are provided below. You see that there is no `time` variable. Indeed, in ROMS the time variables is called `scrum_time`.

Hope this helps

Nicolas

**Comment by silvaglx** [comment]
Thank you very much for your support @barriern 
I'll close the issue since my doubts were solved!
