### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ytmben** [ichthyop/ichthyop#95]
Hello,

I am trying to run a simulation similar to my last one, but for some reason once the simulation gets to my second ocean current .nc, it stops and gives me this error:

`ichthyop[severe] Index -2147483648 out of bounds for length 72 | java.lang.ArrayIndexOutOfBoundsException: Index -2147483648 out of bounds for length 72`

My lat dimension has a length of 72, but I can't understand to what it is referring to with Index -2147483648. 
I already checked if by mistake it's some wrong value in my lat dimension, but from what I could tell it isn't.
Do you have any idea?

Thank you in advance,
Yotam

**Comment by ytmben** [comment]
Just to add, bizarrely enough, that now I tried running a simulation on different ocean current data, on which I have already ran simulations, and I am getting a very similar error:

`ichthyop[severe] Index -2147483648 out of bounds for length 102 | java.lang.ArrayIndexOutOfBoundsException: Index -2147483648 out of bounds for length 102`

Again, 102 is the length of my latitude dimension, which in this case is named lat.
Very strange, but the reappearing thing is the Index -2147483648.

**Comment by ytmben** [comment]
Hi @barriern ,
Thank you for such a quick reply.
I will send them to you by WeTransfer.

Yotam

**Comment by barriern** [comment]
Hi Yotam. 

I received your files but the coordinates files (MED-MFC_006_004_coordinates_crop_upper_lev.nc and MED-MFC_006_004_mask_bathy_crop_upper_lev.nc) are missing. So I can't run the model for the moment

Nicolass

**Comment by ytmben** [comment]
Ah, I am so sorry, I must have forgot to attach them. I will send another email right away.

**Comment by barriern** [comment]
I suspect you inverted the longitude and latitudes of your release stain 

![map](https://github.com/ichthyop/ichthyop/assets/32549583/0e3ac0ab-6085-470d-a666-92294f108eb7)

In red, this is the release stain of your configuration file. It is out of the domain, which is why you have the out of bound error.

If you invert lon_stain and lat_stain parameter (blue point), it works.

Nicolas

**Comment by ytmben** [comment]
Thank you for checking, it's weird that that would be the issue, since I tried changing my release stain or flipping it and I got the an error reading that my release stain was not in water. But maybe I made a silly mistake by mistyping a number.
In any case, thank you for checking and for your patience, and I apologizing for bothering you with such a silly thing.
Yotam

**Comment by ytmben** [comment]
It works as you say, 
Thank you for all your help
